### ISSUE TITLE
Fork jest-dev-server?

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#104]
Hi!

Is there a chance to fork the jest-dev-server into this repo or a separate repo? I just submitted two new issues on jest-dev-server (see https://github.com/smooth-code/jest-puppeteer/issues/341 and https://github.com/smooth-code/jest-puppeteer/issues/342) but the overall repo (https://github.com/smooth-code/jest-puppeteer/commits/master) seems a bit stale, 5 commits in soon 4 months.

Another idea would be to put jest-playwright and all its packages under an organisation instead of under mmarkelov/jest-playwright. E.g. jest-playwright/X or something, so you could bring more packages under there?

I am aware I am going out of my way here for asking for something where you are already donating a great deal of your free time. Which is very much appreciated.

**Comment by mmarkelov** [comment]
@thernstig thank you for your feedback as always)
Put **jest-playwright** under organization may be a good idea, we can also put @mxschmitt packages there. @mxschmitt what do you think about it?

**Comment by thernstig** [comment]
Yes, I've read lots of good about putting it all in one org. It gives a sense of quality for a project, making it more official.

**Comment by mxschmitt** [comment]
makes sense @mmarkelov :)
Have you created an organisation with the name `jest-playwright`?
Seems already taken, weird.

**Comment by mmarkelov** [comment]
@mxschmitt noup, it wasn't me)

**Comment by mxschmitt** [comment]
@thernstig we'll give him 1 week to respond, otherwise we will rewrite the package in TypeScript in a fork.

**Comment by thernstig** [comment]
I did realize 🥂 Nice to see this whole community of packages progressing.

**Comment by thernstig** [comment]
@mxschmitt Any chance you want to fork it :)? I've got three issues reported, no reply:

https://github.com/smooth-code/jest-puppeteer/issues/342
https://github.com/smooth-code/jest-puppeteer/issues/341
https://github.com/smooth-code/jest-puppeteer/issues/340

**Comment by mxschmitt** [comment]
Not sure if we should proceed with that. The future is probably something like that: https://github.com/microsoft/playwright-runner/issues/9

cc @mmarkelov what do you think?

**Comment by thernstig** [comment]
@mxschmitt Interesting. I had missed playwright-runner entirely, thanks. How you do recon that will pan out in relation to jest-playwright?

**Comment by mxschmitt** [comment]
> @mxschmitt Interesting. I had missed playwright-runner entirely, thanks. How you do recon that will pan out in relation to jest-playwright?

It will probably replace jest-playwright in the long term. But still heavily under development.

**Comment by mmarkelov** [comment]
@mxschmitt @thernstig I suppose we should fork it for a while. Cause **playwright-runner** is under development

**Comment by thernstig** [comment]
@mmarkelov If you wish I would of course not mind 😄

**Comment by mmarkelov** [comment]
I think we can close it. We got [`jest-process-manager`](https://github.com/playwright-community/jest-process-manager)

**Comment by mmarkelov** [comment]
@thernstig we just published new prerelease version, it used [`jest-process-manager`](https://github.com/playwright-community/jest-process-manager). You can try it: 
`npm install jest-playwright-preset@next`

**Comment by thernstig** [comment]
Awesome, will try to test this next week. Swamped with work right now. Looking forward to https://github.com/playwright-community/jest-process-manager/issues/4 sometime in the future as well :)

**Comment by thernstig** [comment]
@mmarkelov @mxschmitt I've tested it and it works. Sorry for testing it so late!
