### ISSUE TITLE
Feature request: Opt out of failure on pageerror

### ISSUE THREAD

**Issue by celeryclub** [playwright-community/jest-playwright#107]
Hey team. Got a feature request here. It looks like a `pageerror` will always fail the current test (based on this LOC).
https://github.com/playwright-community/jest-playwright/blob/1dcafbd1426625ee11566654ab5b4d077a50af8e/src/PlaywrightEnvironment.ts#L16

Could we allow this to be turned off? In my use case, I have a third-party script sometimes throws errors that I want to ignore, but I want to know if my first-party scripts throw an error.

Thanks!

**Comment by mxschmitt** [comment]
> Hey team. Got a feature request here. It looks like a `pageerror` will always fail the current test (based on this LOC).
> https://github.com/playwright-community/jest-playwright/blob/1dcafbd1426625ee11566654ab5b4d077a50af8e/src/PlaywrightEnvironment.ts#L16
> 
> Could we allow this to be turned off? In my use case, I have a third-party script sometimes throws errors that I want to ignore, but I want to know if my first-party scripts throw an error.
> 
> Thanks!

Hi there!

would you either want to completely turn this feature on/off or maybe add a custom intercept function, which will do something like `uncaughtExceptionInterceptor: (error) => !error.includes("foo")` in the end to ignore a specific error?

I feel open about both designs, but probably the second one does fit better for your use case right?

**Comment by celeryclub** [comment]
I actually think just disabling would address my use case, since it's easy enough to set up my own `page.on('pageerror')` handler. Thanks!

**Comment by celeryclub** [comment]
Also I'm happy to work on this. I was thinking of perhaps a config option called `failOnPageError` that defaults to `true`. What do you think?

**Comment by mxschmitt** [comment]
> Also I'm happy to work on this. I was thinking of perhaps a config option called `failOnPageError` that defaults to `true`. What do you think?

sounds awesome, yes. `failOnPageError` which is per default `true` sounds great. If you need further advice, let us know. 👍

**Comment by celeryclub** [comment]
Sooo... as soon as I started working on this, I found the existing config option called `exitOnPageError`. But it doesn't seem to be hooked up to anything. Do you know what the story is with that? Should I just wire that on up instead of making a new one?

**Comment by celeryclub** [comment]
I'm going to assume "yes" for now, but obviously happy to change this if you think that makes sense. :)
