### ISSUE TITLE
feat: access current device and browser inside a test

### ISSUE THREAD

**Issue by mxschmitt** [playwright-community/jest-playwright#110]
Maybe just add browser and device to the globals.

cc @mmarkelov

**Comment by mmarkelov** [comment]
@mxschmitt we have browser in global
https://github.com/playwright-community/jest-playwright/blob/8ad11b9e75341bc845c4f8a49d9e7b9ea576abe0/src/PlaywrightEnvironment.ts#L133

Adding current device to the global may be a good idea

**Comment by mxschmitt** [comment]
I mean browser name. But could be fetched via browser.name()
