### ISSUE TITLE
Output error when running headful with no display attached

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#114]
Let's say you ssh to a remote host and run jest-playwright there. Then if you run with `headless=false` you get this error:

```sh
  ● Test suite failed to run

    Protocol error (Target.setAutoAttach): Target closed.
```

It would be nice if it gives an error message that is understandable in this scenario. Is this maybe a Playwright bug?

**Comment by mxschmitt** [comment]
This should be handled better in the Playwright upstream repo in my mind. Something like "No virtual desktop recognised" should be logged from my point of view.

**Comment by thernstig** [comment]
@mxschmitt Will do!

**Comment by thernstig** [comment]
https://github.com/playwright-community/jest-playwright/issues/114
