### ISSUE TITLE
Searching the wrong directory for config when using Jest `projects` option

### ISSUE THREAD

**Issue by l-abels** [playwright-community/jest-playwright#120]
My directory structure looks like this:

```
tests/
  visual-tests/
    jest.config.js
    jest-playwright.config.js
  other-tests/
    jest.config.js
  jest.config.js
```

The outermost Jest config uses the `projects` field to run other Jest projects.  Each project uses its own config file, and `<rootDir>` replacement refers to the folder containing the Jest config specific to that project.

The inner Jest config in `visual-tests` is the one that uses the `jest-playwright-preset`.

Expected behavior:
The runner looks for `jest-playwright.config.js` in `tests/visual-tests/`
Actual behavior:
The runner looks for the file in `tests` and returns the default config.

Note:
When the test actually run, it uses the correct launch options.  So it's looking in the wrong place when getting a list of browsers and devices, but later looks in the correct place for the launch and context options.

**Comment by mmarkelov** [comment]
@l-abels thank you for your report. I just made small repo to represent this bug https://github.com/mmarkelov/jest-playwright-projects-example

And seems like it doesn't work with **jest-playwright-preset@next** but it should work with current version. 

I suppose I can fix it for next release, but to be clear could you provide about your **jest-playwright-preset** version

**Comment by mmarkelov** [comment]
For **next** version seems like it came from here:
https://github.com/playwright-community/jest-playwright/blob/d41ca513b8ce070d2f6d9589455035298602de04/src/PlaywrightRunner.ts#L84
So `this._globalConfig.rootDir` isn't what I expected, seems like that right `rootDir` is in tests config - `tests[0].context.config.rootDir`
