### ISSUE TITLE
Jest Playwright vs Playwright Runner

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#123]
So going forward, I do think Jest Playwright has its place and I am unlikely to change. The reason is, that as far as I understood Playwright Runner, it does not use Jest to launch tests. I deducted this from a comment from the developer of Jest Runner, which stated that it does not run in a vm jescontext. Which Jest does.

If Playwright Runner does not run with Jest as the actual test Runner, it looses a lot of its luster to me. This is because Jest has so many nice built-in functionalities that Playwright Runner could never keep up with. Which this project gets for free since it rides upon Jest. As an example, the various reporters, ways to run tests, to hook into via `handleEvent`, to run both unit and e2e tests with the same tool. I think the last point is my strongest; It means developers in a team only have to learn one CLI to run tests instead of two. Any project is bound to have a lot of complexity and the more it can be reduced, the better and the faster development.

Now, maybe I misunderstood Playwright Runner completely as I did not spend time reading the code or running it, and the docs are not updated yet properly. But I thought it'd be interesting to start a discussion about this here to see what the thoughts are from @mmarkelov and @mxschmitt who are the maintainers of this repo and its utils.

**Comment by thernstig** [comment]
I most likely did misunderstand Playwright Runner since it does use the Jest config, see https://github.com/microsoft/playwright-runner. But then I have no idea how and why it does not run within a vm. Maybe due to the fact that hey implement some kind of custom Jest environment and runner, which means you can decide to not use a vm.

I do however then wonder if it is still possible to run Playwright Runner in parallel. I suppose many of these questions should instead be directed to the Playwright Runner repo.

**Comment by mxschmitt** [comment]
Hey, this project is not related to the `playwright-runner` project. We are using currently for the release candidates a version which uses Jest Runners under the hood, but thats mainly for easing up the process with multiple browsers / devices. (will be released soon to the normal channel)
I also don't know all the details when its using a V8 VM and when not. But that should normally not cause any issues (except `instanceof`). I'm curious what you are trying to archive, is it only the thing with the timeout errors?

```js
import { errors } from 'playwright-chromium'

describe('...', () => {
  it('...', async () => {
    try {
      await page.waitForSelector("#foo", {
        timeout: 10
      })
    } catch (err) {
      console.log(err instanceof errors.TimeoutError, err.name === errors.TimeoutError.name)
    }
  })
})
```

-> instanceof does not work
-> compare the name does work

**Comment by thernstig** [comment]
@mxschmitt I certainly understand that this project is not related to `playwright-runner` 😃 It also has nothing to do with that specific `instance of` issue.

The point of this issue was to understand the differences between using `jest-playwright` and `playwright-runner`. It's entirely possible this is impossible to answer now as `playwright-runner` is under development.

Many projects have a "comparison" in the README to other tools, why ones is better than the other or just stating the differences. E.x in the Python world: https://github.com/python-poetry/poetry#what-about-pipenv

Does it make it more clear what I am wondering about?

**Comment by mxschmitt** [comment]
I would not make a comparison until playwright-runner is not fully ready.

Differences in my mind (@mmarkelov please add more / feel free to edit):
- jest-playwright: has support for custom launch/context options
- playwright-runner: native support for TypeScript
- jest-playwright needs e.g. [jest-ts](https://github.com/kulshekhar/ts-jest)
- both have support for multiple browsers
- both are based on the Jest runner API
- playwright-runner will get his page object via the callback parameters. jest-playwright uses globals for that.

**Comment by mmarkelov** [comment]
@thernstig yeah! I agree with @mxschmitt that it’s very difficult to make comparison right now. **playwright-runner** may be a good solution, when it will be ready. For now I don't have any plans about stopping maintain this library. We should wait until the **playwright-runner** will be ready. And then we could make decisions about future.

**Comment by thernstig** [comment]
That is great news, that is something I was afraid of 😃

**Comment by mxschmitt** [comment]
Closed for now. 👍
