### ISSUE TITLE
Unable to run specs in v0.2.1

### ISSUE THREAD

**Issue by celeryclub** [playwright-community/jest-playwright#129]
Hey team. I'm afraid that v0.2.1 may have introduced a bug. After upgrading I'm unable to run any specs at all. It always gives me `Test Suites: 0 of x total`, whether or not I filter by filename.

```sh
npm run e2e:stage:headed -- test/e2e/specs/search/load.critical.ts

> be.net@0.0.0 e2e:stage:headed /Users/steve/adobe/behance/be.net
> cd test/e2e && PLAYWRIGHT_ENVIRONMENT=stage HEADED=true npx jest --runInBand "test/e2e/specs/search/load.critical.ts"

Test Suites: 0 of 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.105 s
Ran all test suites matching /test\/e2e\/specs\/search\/load.critical.ts/i.
```

**Comment by mmarkelov** [comment]
@celeryclub was it ok in previous version?

**Comment by celeryclub** [comment]
Yes v0.2.0 works well for me.

**Comment by mmarkelov** [comment]
@celeryclub thanks for report. Try to fix it

**Comment by mmarkelov** [comment]
@celeryclub it was silly bug, I just fixed it and published new version.You can take a look

**Comment by celeryclub** [comment]
Thanks for the quick turnaround @mmarkelov!
