### ISSUE TITLE
browsers.flatMap is not a function

### ISSUE THREAD

**Issue by mxschmitt** [playwright-community/jest-playwright#136]
```
TypeError: browsers.flatMap is not a function
    at Promise.all.tests.map (/home/runner/work/try-playwright/try-playwright/tests/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:36:25)
```

Solution would be either to polyfill it manually or to use babel with the typescript preset for transcompiling the source code.

Probably the easiest would be to use that: https://www.npmjs.com/package/array.prototype.flatmap

Seems to be well maintained and famous.

**Comment by mmarkelov** [comment]
@mxschmitt I just replaced it in #131, but it wasn't published yet, so I just publish **0.2.3**
