### ISSUE TITLE
Expose BrowserType via some means for tests or jest-circus 

### ISSUE THREAD

**Issue by pavanreddy61** [playwright-community/jest-playwright#141]
I was thinking to take screenshots and separate them with browserName ... as sameSpecName error screenshots override each other. Was using jest-circus and defined browsers array in **jest-playwright.config**

Or Is this already exposed somehow?

**Comment by mxschmitt** [comment]
Hi, yep it is, as `browserType` (global var). We should document it somewhere.
Ref: https://github.com/playwright-community/jest-playwright/blob/master/src/PlaywrightEnvironment.ts#L88

**Comment by pavanreddy61** [comment]
THanks @mxschmitt It works now

**Comment by mxschmitt** [comment]
Want to keep it open until we have documented the globals.
