### ISSUE TITLE
feat: custom playwright instance from config 

### ISSUE THREAD

**Issue by alexgwolff** [playwright-community/jest-playwright#148]
Hi, I have a project more or less like react-create-app.
When jest-playwright try resolver playwright instance from project.json there any playwright in dependencies or devdependencies so this fail, because jest and playwright living in another package.
Theres some way to define playwright instance from jest config files?
 
thanks

**Comment by mmarkelov** [comment]
@alexgwolff thanks for the report. Seems like the check of `package.json` for `playwright` instances should be rewritten.
