### ISSUE TITLE
feature: Allow browser specific launch arguments

### ISSUE THREAD

**Issue by mxschmitt** [playwright-community/jest-playwright#156]
Not sure whats the best way for integrating this feature, either with callbacks or with something else.

Use case:
- Environment which uses user root
- Tests multiple browsers including chrome
- Chrome won't start because --no-sandbox argument was not specified.

Requested by @arjun27 via Slack.

**Comment by mmarkelov** [comment]
> We can create a function so that we can use this for launch/connect/newContext options.

Yeah, sure. I'll take a look
