### ISSUE TITLE
Performance issue and websocket error

### ISSUE THREAD

**Issue by DavidZidar** [playwright-community/jest-playwright#158]
I just upgraded to version 1.0.0 and immediately noticed that my test suite takes much longer to run, now about 18 seconds when it finished in about 10 seconds before. My guess is there is something slow going on during startup because the first test result takes much longer to show up as done.

Even worse, every other time or so that I run my tests I get the following error during startup:
```
C:\path_to_project\node_modules\playwright-chromium\lib\server\chromium.js:211
            session.queue.push(parsedMessage);
                          ^

TypeError: Cannot read property 'push' of undefined
    at WebSocket.<anonymous> (C:\path_to_project\node_modules\playwright-chromium\lib\server\chromium.js:211:27)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\path_to_project\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\path_to_project\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (C:\path_to_project\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (C:\path_to_project\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (C:\path_to_project\node_modules\ws\lib\receiver.js:74:10)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Receiver.Writable.write (_stream_writable.js:303:10)
```

This is not an error that I have seen before and when I revert to version 0.2.5 these issues go away.

**Comment by mxschmitt** [comment]
Hi @DavidZidar, which version of Playwright are you using? Playwright has afaik currently on the latest version with performance.

**Comment by mmarkelov** [comment]
@DavidZidar thank you for report. It will be nice if you could provide some more details. Your configuration, tests example, cause right now it's quite difficult to say what is wrong.
@mxschmitt what do you think about it? Seems like that problem could be in #134, #138 or #147

**Comment by DavidZidar** [comment]
@mxschmitt I'm using Playwright v1.1.1 both before and after, the only thing I changed was jest-playwright-preset version.

@mmarkelov Any specific thing you need to know about the configuration?

**Comment by mxschmitt** [comment]
@DavidZidar are you having multiple test files? multiple browsers / devices?

**Comment by DavidZidar** [comment]
Currently have 7 test files that Jest runs in parallell, they test two related websites running locally on my machine and I'm only using `playwright-chromium`.

**Comment by mmarkelov** [comment]
@DavidZidar can you try **1.0.0-rc1** version? 
@mxschmitt if the issue will be reproduced in **1.0.0-rc1**, that seems like something is wrong with reusing browser

**Comment by DavidZidar** [comment]
Just tried 1.0.0-rc1 and I'm still seeing the same issue

**Comment by DavidZidar** [comment]
I only see one chromium instance opening though

**Comment by mmarkelov** [comment]
@mxschmitt maybe we can make reusing browser optional? Cause right now I don't have ideas how to fix it

**Comment by mxschmitt** [comment]
> @mxschmitt maybe we can make reusing browser optional? Cause right now I don't have ideas how to fix it

I'll try to make a test to find out the cause for it instead of dropping the whole thing. Since its only a performance topic which adds a few seconds, I would only consider it as a medium issue instead of a super critical one.

**Comment by DavidZidar** [comment]
It is not only a performance issue, the tests completely fail to run when the error is thrown.

I see it happening mostly when I try running the tests twice in a row.

**Comment by mxschmitt** [comment]
@DavidZidar you are on Windows right? Thats maybe the issue, I can try to setup a VM and debug it myself.

**Comment by DavidZidar** [comment]
@mxschmitt That's right, I'm on Windows. I created this minimal repo https://github.com/DavidZidar/jest-playwright-preset-bug and can reproduce the issue fairly easily by running `yarn test` a couple of times.

While trying to reproduce the error this new error happened once, the last test never even finished, I aborted after a minute or so.
```
 PASS   browser: chromium  tests/two.test.js
 PASS   browser: chromium  tests/three.test.js
 PASS   browser: chromium  tests/four.test.js
 FAIL   browser: chromium  tests/one.test.js
  ● Test suite failed to run

    TimeoutError: Timeout 30000ms exceeded during chromium.connect.
    ================== chromium.connect logs ==================
    <ws connecting> ws://127.0.0.1:63171/46708a7182b95e66e568342e5eb20910
    <ws connected> ws://127.0.0.1:63171/46708a7182b95e66e568342e5eb20910
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

      at ProgressController.run (node_modules/playwright-chromium/lib/progress.js:72:30) 
```

**Comment by mmarkelov** [comment]
@DavidZidar thank you for representation repo. I just tried to run it with Mac and it is OK. Seems like @mxschmitt is right, cause it maybe something that related to Windows
<img width="397" alt="Снимок экрана 2020-06-24 в 15 30 17" src="https://user-images.githubusercontent.com/22371328/85556937-fe09e180-b62f-11ea-9cb3-fc8eadbea8d3.png">

**Comment by DavidZidar** [comment]
You may be right. To be clear though the error doesn't happen every time, I tried it again and had to run it four times before the error happened this time.

**Comment by mxschmitt** [comment]
@mmarkelov we can try to run the examples repository on windows. Maybe then we can quickly see if something goes wrong.

**Comment by mxschmitt** [comment]
I've tested jest-playwright on windows: https://github.com/playwright-community/jest-playwright/pull/166 and the examples repository, which are also passing (except one which is already fixed upstream and has nothing to do with this issue) https://github.com/playwright-community/playwright-jest-examples/pull/10/checks?check_run_id=803718562. So could you give us maybe more information about your environment? Which version e.g. or are there specific firewall rules applied somehow?

**Comment by DavidZidar** [comment]
Hmm, to take the specific machine out of the question as it is a corporate laptop that I don't have full control over I tried reproducing the issue on my home workstation. At first I didn't have much success as the tests ran too quickly so Jest started running them in series instead of in parallel. My home workstation also has a lot more CPU cores so that may also be an issue.

I was however able to reproduce the issue at least once on this completely separate machine as well by introducing an artificial delay in the tests and adding a bunch more tests. I have pushed a new commit to my repro with the changes.

**Comment by DavidZidar** [comment]
Oh, and if it helps, both machines are running Windows 10 (but different versions, 1809 and 2004) and NodeJS version 14.4.0.

**Comment by mxschmitt** [comment]
Thanks! Will check it out later. So it's reproducible on both Windows 10 versions?

**Comment by DavidZidar** [comment]
> So it's reproducible on both Windows 10 versions?

Yes, that's right. I have a harder time reproducing it on my home workstation though, but these are all the classic smells of a race condition.

**Comment by mxschmitt** [comment]
@DavidZidar could you try to use the `@next` versions of Playwright? These are the bleeding edge versions, it seems like it's already fixed upstream. So just `yarn add playwright-chromium@next` in the case with the reproducible.

Before with 1.1.1: 3/5 runs failed
After with `@next` 0/5 runs failed

**Comment by DavidZidar** [comment]
Just tried upgrading to `playwright-chromium@next` and I can confirm the crashing issues I've had are gone! Great success.

It is still running much slower than before though, but that's not as bad as outright crashing.

**Comment by mmarkelov** [comment]
@DavidZidar with **next** version you are able to configure launch type of browser. So you can try, I hope it will will help your performance isuue:
```js
// jest-playwright.config.js
module.exports = {
    launchType: 'LAUNCH',
}
```

**Comment by DavidZidar** [comment]
@mmarkelov Hey, thanks for the update! I'm on vacation for a couple of weeks so I can't try it out right now, either a colleague of mine will try it out or I'll try it some time in august.

**Comment by olsch** [comment]
@mmarkelov I can verify that the next version of jest-playwright-preset (currently 1.3.0-rc1) together with next version of playwright-chromium (1.2.0-next.1594082323189) solves the performance issue that @DavidZidar reported above (#158)  as long as you use `launchType: 'LAUNCH'`. Also, the crash issue appears to be gone.
When I run my tests (8 test suites / 58 tests) with `launchType: 'PERSISTENT'` the behaviour is erratic. Only one of 5+ testruns finished successfully. The others were either hanging after the last testrun or crashing with the message _A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown._. When I tried  `launchType: 'PERSISTENT'` with v1.2.1 I didn't have any of these problems.
Running with  `launchType: 'SERVER'` works fine but is very slow.
BTW, I'm a colleague of @DavidZidar.

**Comment by mmarkelov** [comment]
@olsch thank you for your response. I just don't have enough experience with **persistent** launching. And there are some issues related to this type:
https://github.com/playwright-community/jest-playwright/issues/188#issuecomment-654224818
Also core playwright team recommend to use **launch** instead of **persistent**
https://github.com/microsoft/playwright/issues/2828#issuecomment-653579598

Fixing https://github.com/playwright-community/jest-playwright/issues/188 may help, but for now I'm not sure
