### ISSUE TITLE
Subsequent tests within the same spec runs within the same page with hashrouting

### ISSUE THREAD

**Issue by axis-magnusd** [playwright-community/jest-playwright#165]
When running multiple tests within a single spec and utilising hash routes the page object does not appear to reload the page, causing inter test dependencies- ie. all the tests will leave their state for the upcoming test case.

Would it be possible to either make the current behaviour an opt-in per spec or expose an option to opt-out if this will continue to be the default behaviour?

**Comment by mmarkelov** [comment]
@axis-magnusd thank your for report. Could you please provide some general wrong tests?

**Comment by narthollis** [comment]
I ended up adding
```
beforeEach(async () => {
    await page.goto(URL);
});
```

to each of my describe blocks

**Comment by axis-magnusd** [comment]
This is resolved by using:
```typescript
await jestPlaywright.resetPage();
```
