### ISSUE TITLE
Run multiple browsers at the same time

### ISSUE THREAD

**Issue by forxtu** [playwright-community/jest-playwright#172]
Hey!

I want to run multiple browsers for each test and I see that you have `browsers` option for `jest-playwright.config.js` file.
But it doesn't work for me as it should. It opens all of the listed browsers but doesn't open test cases on them.

Am I doing something wrong or this options is not working as it supposed too? Any help or working examples of implementation will be highly appreciated!

Thanks!

![image](https://user-images.githubusercontent.com/18015187/85743535-c755c900-b70c-11ea-98fc-5c08b6ae0b72.png)

**Comment by mxschmitt** [comment]
Hey!

could you provide us maybe your `jest-playwright.config.js` and a minimal test?

Here you can find a few examples which should demonstrate how it works: https://github.com/playwright-community/playwright-jest-examples/tree/master/basic

**Comment by forxtu** [comment]
@mxschmitt  thanks for the answer!

`jest-playwright.config.js` is pretty straightforward

```
module.exports = {
  browsers: ['chromium', 'firefox', 'webkit'],
  launchOptions: {
    headless: false
  }
}
```

I see that in examples that you provided before you use `page` as global object, and I got an `undefined` if I try to use it as global. Should I declare it somehow? I found related topics to global installation for puppeteer, and I think for playwright it should be pretty similar, but I can't find a proper way to do it.

**Comment by mmarkelov** [comment]
@forxtu `page` can be not defined, if you don't pass `jest-playwright-preset` to `jest`:
https://github.com/playwright-community/jest-playwright#usage

**Comment by forxtu** [comment]
@mmarkelov I have preset property set. I use 2 separate configs `jest.config.js` and `jest.e2e.config.js`. I've tried different options - set preset in package.json, in jest config and in separate configs. Still keep getting `undefined`. Should I setup globals in jest config and create my own environment with setup as in puppeteer?

**Comment by mmarkelov** [comment]
@forxtu I'm not sure about you issue. I can be related to [ESLint globals](https://github.com/playwright-community/jest-playwright#eslint-globals--page-is-not-defined)

But it also can be `undefined` if `jest-playwright-preset` was not set correctly

**Comment by forxtu** [comment]
@mmarkelov Oh I've managed to make it work - I had jest-environment set to "jsdom" that's why I had `page` as `undefined`. I've changed it and now it works.

Thanks for your help and great libs :)
