### ISSUE TITLE
[Question / Feature Request] Skip test for some browser/device combinations

### ISSUE THREAD

**Issue by narthollis** [playwright-community/jest-playwright#174]
If we need to run a device / browser specific test, what is the best way of executing this?

From what I can see, the best way to do this currently would be an condition at the start of the test checking `browserName` and `deviceName` and returning early if the test should not be executed for this device/browser.

```typescript
it('should only run for webkit and iOS', async () => {
    if (!(browserName === 'webkit' && deviceName.startsWith('iOS')) {
        return;
    }

    ... test here ...
});
```

Is this the best way of skipping tests for some browsers/devices? Is there a better way currently? Would it possible to support a more declarative way to do this?

**Comment by mmarkelov** [comment]
@narthollis it will be a useful feature. It will be nice to use it in `jest` style, like so:
```js
test.skipPlaywright({browser, device}, 'my only true test', () => {
    expect(1 + 1).toEqual(1);
});
```

I'm not sure if it will be easy to implement, but I'll try

**Comment by jhildenbiddle** [comment]
@mmarkelov --

How do we specify multiple browsers and/or devices? The [docs](https://github.com/playwright-community/jest-playwright#skip-tests-for-specific-browser-and-device) state this is possible:

> It's possible to skip tests for browser or combination of browser and device

My assumption was to set the `browser` value to an array (below) but this did not work.

```js
jestPlaywright.skip({ browser: ['chromium', 'firefox'] }, () => {
  // ...
})
```

**Comment by mmarkelov** [comment]
@jhildenbiddle this is because we expect that single browser will be passed. I suppose that we need to be consistence and use array for this purpose, like in `jest-playwright.config`. I'll take it. Thanks!

**Comment by jhildenbiddle** [comment]
Thanks, @mmarkelov!
