### ISSUE TITLE
TypeError: Cannot destructure property 'name' of 'device' as it is null.

### ISSUE THREAD

**Issue by p0x6** [playwright-community/jest-playwright#176]
getting this error when trying to run tests

**Comment by mxschmitt** [comment]
Could you provide us your jest-playwright.config.js?

**Comment by p0x6** [comment]
sure!

here's the `jest-playwright.config.js`

```
module.exports = {
  launchOptions: {
    headless: false
  }
}
```

i'm using 1.1.0

**Comment by p0x6** [comment]
i'm also trying to integrate with `jest-runner-groups` so i can separate out the mock backend tests for integration and the live api calls for e2e. i think that's what's causing the issue

**Comment by p0x6** [comment]
yea, removing jest-runner-groups fixed the error. to run different sets of tests, i'll probably need to have multiple jest configs and tests either in different folders or have different names. is there a better way to do this?

**Comment by mmarkelov** [comment]
@p0x6 I just look through `jest-runner-group` and it is using custom test runner under hood, just like `jest-playwright`. So you got this error. I'm not sure, but maybe setting [`projects`](https://jestjs.io/docs/en/22.x/configuration#projects-arraystring--projectconfig) in your **jest config** will help you

**Comment by karthikiyengar** [comment]
Also running into this.
```
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
at CustomEnvironment.setup (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:69:54)
```

Where PlaywrightEnvironment is
```
const PlaywrightEnvironment = require('jest-playwright-preset/lib/PlaywrightEnvironment').default

class CustomEnvironment extends PlaywrightEnvironment {
  async setup() {
    await super.setup()
    // Your setup
  }

  async teardown() {
    // Your teardown
    await super.teardown()
  }
}

module.exports = CustomEnvironment
```

jest.config has the following options
```
"testEnvironment": "<rootDir>/tests/jest-setup/customTestEnvironment.js",
"testRunner": "jest-playwright-preset/lib/PlaywrightRunner",
```

**Comment by karthikiyengar** [comment]
This probably comes down to https://github.com/playwright-community/jest-playwright/blob/master/src/PlaywrightEnvironment.ts#L108 - a `!=` instead of a `!==` would fix this issue.

**Comment by thernstig** [comment]
Also getting this when I upgraded from `0.1.3` to `1.2.0`. I am using a custom environment. Here is a minimal repro with a minimal custom environment:

```javascript
const PlaywrightEnvironment = require('jest-playwright-preset/lib/PlaywrightEnvironment')
  .default;

class CustomEnvironment extends PlaywrightEnvironment {
  constructor(config) {
    super(config);
    this.config = config;
  }

  async setup() {
    await super.setup();
  }
}

module.exports = CustomEnvironment;
```

It fails on the `await super.setup();` with the error `TypeError: Cannot destructure property `name` of 'undefined' or 'null'.`

Really want to upgrade to verify using https://github.com/playwright-community/jest-process-manager as I promised to do 😃

**Comment by mmarkelov** [comment]
It seems like that the last two comments are not related to the original issue. I steel can't reproduce this bug, but it seems like that there is some cases when `device` is `undefined`, which cause this bug. I'll merge #189, seems like it will fix this one.

**Comment by thernstig** [comment]
Wrote new issue here: https://github.com/playwright-community/jest-playwright/issues/190
