### ISSUE TITLE
Is playwright-core node module is needed to get types

### ISSUE THREAD

**Issue by vrknetha** [playwright-community/jest-playwright#177]
Using jest playwright preset,

I have done all the configuration mentioned in the documentation but i am not getting any types while coding. I have not installed playwright core but i have installed total playwright node module.

But the global.d.ts import the modules from playwright-core. Due to that, i am not getting intellisense. But , once i change the import from playwright-core to playwright. Its working fine. Check the screenshots

![image](https://user-images.githubusercontent.com/20596261/85951128-c2984b80-b97e-11ea-89ea-7295a06aa7bd.png)
![image](https://user-images.githubusercontent.com/20596261/85951131-c75cff80-b97e-11ea-95b9-e6aff06e0ce2.png)
![image](https://user-images.githubusercontent.com/20596261/85951134-ca57f000-b97e-11ea-90b9-7e249e4ff618.png)
![image](https://user-images.githubusercontent.com/20596261/85951140-ce840d80-b97e-11ea-9d7f-11193b3c756c.png)

How to solve this issue?

**Comment by mxschmitt** [comment]
Thats an upstream issue, already tracked here: https://github.com/microsoft/playwright/issues/2540

As a workaround, you can install `playwright-core` manually.

**Comment by vrknetha** [comment]
Thank you for getting back ...quickly. I will do a manual install.
