### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by jakobrosenberg** [playwright-community/jest-playwright#179]
I've installed `jest-playwright-preset`, but am not getting any code completion in VS Code.

I've tried 
```javascript
/// <reference types="jest-playwright-preset" />
```
and
```javascript
require('jest-playwright-preset')
```

Both methods get rid of the red underlining of `page`, but neither adds completion.

I didn't find any documentation on how to achieve this.

**Comment by mxschmitt** [comment]
Hey, there is unfortunately currently an upstream bug on Playwright side. Thats why you have to install playwright-core manually.

Closing since already tracked in #177
