### ISSUE TITLE
[Feature Request] Add resetPage & resetBrowser(/context) apis

### ISSUE THREAD

**Issue by Bnaya** [playwright-community/jest-playwright#180]
First, i want to thank you for this amazing library!

jest-puppeteer have apis to reset the page and browser for the current environment. 
https://github.com/smooth-code/jest-puppeteer#globaljestpuppeteerresetpage

That's very helpful, if for example i want new page for each test.
So i can do something like:

```js
beforeEach(async () => {
  await jestPuppeteer.resetPage()
});
```

It will be very helpful to have it also for jest-playwright

Thanks!

**Comment by mmarkelov** [comment]
@Bnaya thank you for your report. I think we can make it)

**Comment by Bnaya** [comment]
Thank you very much @mmarkelov !
