### ISSUE TITLE
page is not defined

### ISSUE THREAD

**Issue by jakobrosenberg** [playwright-community/jest-playwright#181]
Getting `page is not defined` when running jest.

I've installed
`jest-playwright-preset`
`playwright-core`
`playwright`

and added the preset to my `jest.config.js`.
`preset: 'jest-playwright-preset'`

**Comment by mxschmitt** [comment]
Are you using TypeScript?
Does this error come from ESLint?

**Comment by jakobrosenberg** [comment]
Using javascript. AFAIK it doesn't come from javascript.

![image](https://user-images.githubusercontent.com/4153004/86058605-770a9e00-ba61-11ea-83e8-d6d60ed6753a.png)

**Comment by mxschmitt** [comment]
How do you start your Jest tests? (maybe script section of your package.json)?
It seems like the jest environment is not correctly configured, so maybe you are using another Jest config e.g. in the package.json.

**Comment by jakobrosenberg** [comment]
package.json
```json
    "test": "jest"
```

command:
``pnpm run test -- integration``

I did have jest configred in package.json at one point, but removed it.

**Comment by ubcent** [comment]
Hi guys. I'm having the same issue. It seems like something was broken in the latest versions. I managed to make it work on the 1.0.1 version. The problem is with globals, so, browser, browserName, and all the rest are not visible in the spec-files.

**Comment by mxschmitt** [comment]
Hi, could you share your configuration files with us? The latest versions were all fine, see here in the CI pipeline where we test them. There you can also obtain working configurations for different scenarios: https://github.com/playwright-community/playwright-jest-examples

**Comment by ubcent** [comment]
The problem is not in the configuration itself, I tried the configurations from the link provided, but it doesn't work even on the bare-metal project. As I said previously I managed to start it on the 1.0.1 version only. The fact that all the tests are passed doesn't guarantee that everything works properly.

**Comment by mmarkelov** [comment]
@ubcent it's very difficult to understand what can be wrong without any provided information.

**Comment by ubcent** [comment]
@mmarkelov sure. What information do you need?

**Comment by ubcent** [comment]
jest.config.js:
```
module.exports = {
  testMatch: ['**/*.e2e-spec.ts'],
  transform: { '^.+\\.ts$': ['ts-jest'] },
  preset: 'jest-playwright-preset',
  globals: {
    'ts-jest': {
      tsConfig: 'tsconfig.spec-e2e.json',
    },
  },
};
```

tsconfig.spec-e2e.json:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "types": ["jest", "jest-playwright-preset"]
  }
}
```

jest: 26.0.1
ts: 3.5.3
playwright: 1.1.0

**Comment by mmarkelov** [comment]
@ubcent as much as possible. Your operation system, maybe some test examples. If you said that it was ok in **1.0.1**, what the first version that cause an error. It was quite enough changes from **1.0.1** to **1.2.1**, so it will be nice if we can detect the first wrong version

**Comment by ubcent** [comment]
@mmarkelov I started my experiments just today. So, I started from the latest (1.2.1), and after a while, I decided to downgrade. I ran through all the versions from 1.2.1 to 1.0.1, the first that works for me is 1.0.1.

OS: macOS 10.15.5 (19F101)

**Comment by ubcent** [comment]
Test example:

```javascript
describe(`Comet UI Tests`, () => {
  let page;

  beforeAll(async () => {
    page = await browser.newPage();

    await page.goto('http://localhost:4200');
  });

  afterAll(async () => {
    await browser.close();
  });

  it(`1. Should load the main page in ${browserName}`, async () => {
    await page.waitForSelector('mat-icon.cmt-bell');
    expect(await page.title()).toBe('Comet');
  });
});
```

**Comment by mmarkelov** [comment]
@ubcent sorry for late response. I can confirm that there is a problem with ts declaration file.
ts 3.5 just don't like this imports:
```js
import type {
  Page,
  Browser,
  BrowserContext,
  BrowserType as PlaywrightBrowserType,
  ChromiumBrowser,
  FirefoxBrowser,
  WebKitBrowser,
} from 'playwright-core'
```

I'll fix it in new release

**Comment by ubcent** [comment]
@mmarkelov Thanks. You are right TS version was a root cause of this issue. The upgrade to the latest resolved that.
