### ISSUE TITLE
Websocket is not open: readyState 3

### ISSUE THREAD

**Issue by forxtu** [playwright-community/jest-playwright#186]
Hi! I ran into an issue with web socket. 

I found this snippet for puppeteer.

```
const setup = async () => {
    browser = await puppeteer.launch({
        args: ['--disable-gpu', '--no-sandbox', '--disable-dev-shm-usage']
    });

    browser.on('disconnected', setup);
};
```

But in case of `jest-playwright` we don't run `.launch` method manually in test, we just use global `page` to go to particular `url`. How I can re-run browser if it fails?

This issue is a bit weird because it occurs once and then if you re-run test it works (but in case of CI it always fails 1st time and it is a problem). And usually it happens with Webkit. Hope it helps.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/18015187/86343366-89ebc100-bc61-11ea-83fb-500d24710d7d.png">

<img width="1046" alt="Screenshot 2020-07-01 at 12 07 28" src="https://user-images.githubusercontent.com/18015187/86342797-c4089300-bc60-11ea-92ed-2c73318dc7db.png">

**Comment by mxschmitt** [comment]
Hi, seems like you have not all the needed dependencies installed. Could you try to use this GitHub Action before?

https://github.com/microsoft/playwright-github-action

it will install all the needed dependencies.

**Comment by forxtu** [comment]
I have it in my GH actions. The thing is this issue occurred locally too.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/18015187/86346131-282d5600-bc65-11ea-8bfa-a8ab54b28ceb.png">

**Comment by mxschmitt** [comment]
Which version of Playwright are you using?

**Comment by forxtu** [comment]
```
"jest-playwright-preset": "^1.1.0",
"playwright": "^1.1.1",
```

**Comment by mxschmitt** [comment]
@forxtu could you try to install playwright@next and to check if it still happens? If I remember correctly, this was a temporary issue by Playwright itself and might be already fixed in their next release.

**Comment by forxtu** [comment]
Thanks for the help @mxschmitt . I'll try it.
