### ISSUE TITLE
Not possible to run custom environment - error output: TypeError: Cannot destructure property 'name' of 'undefined' or 'null'

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#190]
Getting this when I upgraded from `0.1.3` to `1.2.0`. I am using a custom environment. Here is a minimal repro with a minimal custom environment:

```javascript
const PlaywrightEnvironment = require('jest-playwright-preset/lib/PlaywrightEnvironment')
  .default;

class CustomEnvironment extends PlaywrightEnvironment {
  constructor(config) {
    super(config);
    this.config = config;
  }

  async setup() {
    await super.setup();
  }
}

module.exports = CustomEnvironment;
```

It fails on the `await super.setup();` with the error `TypeError: Cannot destructure property 'name' of 'undefined' or 'null'.`

Really want to upgrade to verify using https://github.com/playwright-community/jest-process-manager as I promised to do 😃

**Comment by mmarkelov** [comment]
@thernstig I just published **1.2.1**, hope it will help

**Comment by thernstig** [comment]
Will test and come back to you!

**Comment by thernstig** [comment]
I can verify that it works with `1.2.1`! 🎉
