### ISSUE TITLE
slowMo in launch options is not passed correctly

### ISSUE THREAD

**Issue by achwilko** [playwright-community/jest-playwright#203]
Unfortunately, `slowMo` (https://playwright.dev/#version=v1.2.0&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-slowmo) param is not passed correctly in jest-playwright launch options.

To reproduce, try below jest-playwright.config file:
```js
// jest-playwright.config.js
module.exports = {
  launchOptions: {
    args: ['--no-sandbox', '--disable-dev-shm-usage'],
    headless: false,
    slowMo: 250,
  },
  browsers: ['chromium'],
};

```

 - OS: Windows
 - playwright version 1.1.1.
 - jest-playwright-preset version 1.2.1

![image](https://user-images.githubusercontent.com/5947081/86759935-24267d00-c045-11ea-9549-31bb7ef237b3.png)

**Comment by mmarkelov** [comment]
@achwilko thank you for report. There is some issue with passing `connectOptions`.
Also I got some notes to specify what is wrong with it.
`jest-playwright` under hood is launch [browser server](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsertypelaunchserveroptions) by default. After this it will connect to running server and it will use `connectOptions` passing through the config.
In next release we made this process configurable. So you can just launch the browser:
```js
// jest-playwright.config.js
module.exports = {
  launchType: 'LAUNCH',
  launchOptions: {
    args: ['--no-sandbox', '--disable-dev-shm-usage'],
    headless: false,
    slowMo: 250,
  },
  browsers: ['chromium'],
};
```

Also I just made a fix in #202 to pass `connectOptions`, so after it, you can do something like this:
```js
// jest-playwright.config.js
module.exports = {
  launchOptions: {
    args: ['--no-sandbox', '--disable-dev-shm-usage'],
    headless: false,
  },
  connectOptions: {
    slowMo: 250,
  },
  browsers: ['chromium'],
};
```

**Comment by achwilko** [comment]
@mmarkelov that's great, thanks for the information. I will use `connectOptions` with the next release. Thanks for all your hard work done for `jest-playwright-preset` 🍻

**Comment by mmarkelov** [comment]
@achwilko just published new **next** release, that should fix this issue

**Comment by achwilko** [comment]
@mmarkelov I've just tested `1.3.0-rc2` version and it's working as expected 👍 Once more, thanks for your support and update 🍻
