### ISSUE TITLE
resetContext should accept options for new context

### ISSUE THREAD

**Issue by creage** [playwright-community/jest-playwright#212]
**Is your feature request related to a problem? Please describe.**
In our tests we need to run a page using different users, and we used to reset context, and set new HTTP credentials. But recent version of Playwright warns that 

``warning: method |context.setHTTPCredentials()| is deprecated. Instead of changing credentials, create another browser context with new credentials.``

**Describe the solution you'd like**
`jestPlaywright.resetContext()` creates new context already, but with context options defined in its initial config. It would be nice if this method can accept additional context options, and merge them with initial options.

**Describe alternatives you've considered**
We are already using custom Playwright environment, and we can just overwrite `resetContext` method with our custom implementation, but we believe this feature would give value to entire community.

**Comment by mmarkelov** [comment]
@creage make sense. Thanks for your report

**Comment by creage** [comment]
@mmarkelov thank you very much. When should we expect a new release with this fix?

**Comment by mmarkelov** [comment]
@creage it is available in **next** release. I hope the next stable version will be ready on the next week
