### ISSUE TITLE
 Protocol error (Target.setAutoAttach): Target closed in Docker - Azure CI Linux Agent

### ISSUE THREAD

**Issue by diego-s-lopez** [playwright-community/jest-playwright#236]
**Describe the bug**
Running tests in Azure CI, inside Docker, fail with error:
` Protocol error (Target.setAutoAttach): Target closed.`...
[tasklog_10.log](https://github.com/playwright-community/jest-playwright/files/4950251/tasklog_10.log)

**To Reproduce**
I have a non-preset version working:
[working.zip](https://github.com/playwright-community/jest-playwright/files/4950256/working.zip)

The release pipeline steps are:
`PULL the image`
`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm install`
Run the tests: `docker container run -i --rm -v $PWD:$PWD -w $PWD --ipc=host --security-opt seccomp=chrome.json aws-ecr/playwright-browsers:1.1.1 npm run test preRelease/`

But, with the "preset-version" it doesn't work:
[non-working.zip](https://github.com/playwright-community/jest-playwright/files/4950262/non-working.zip)

Release pipeline steps are the same as previous.

**Expected behavior**
The non-working version works fine in localhost (ubuntu 18.04), and with the docker command, but not inside de Azure CI (Self hosted linux agent)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04 and Self hosted linux agent]
 - Playwright version: 1.1.1
 - jest-playwright version 1.2.1

**Additional context**
I tried updating the playwright version to 1.2.1 but still the same

Thanks for your help and sorry for my english!

**Comment by mxschmitt** [comment]
Hi, could you try to set the environment variable `DEBUG=*` and then check the output? This enables debug logging which would log missing dependencies e.g. to the stdout.
My guess is that not all dependencies are installed or that you try to start chrome as root e.g. But the logs should give us a more specific reason whats going wrong.

**Comment by diego-s-lopez** [comment]
Hi! Thanks for your response.

Here is the log: 
[tasklog_12.log](https://github.com/playwright-community/jest-playwright/files/4953371/tasklog_12.log)

I'm using the preset: jest-playwright-jsdom, version 0.0.3.
I have an oppened ticket with them, and after update to 0.0.4 version, update "playwright" to 1.2.1 version, and add `args:["--no-sandbox"],` in jest-playwright.config.js, the errors changed completely and now, it doesn't work in localhost neither.
New log: 
[tasklog_11.log](https://github.com/playwright-community/jest-playwright/files/4953417/tasklog_11.log)

Reduced tests (for shorter log) in Localhost log with dependencies: ` "jest-playwright-jsdom": "0.0.4",
    "jest-playwright-preset": "^1.2.1",
    "playwright": "^1.2.1"` and `--no-sandbox`
[localhost.log](https://github.com/playwright-community/jest-playwright/files/4953527/localhost.log)

If i remove the "no--sandbox", webkit starts to work, but chromium fail in CI. If i add it, webkit fail both and chromium seems to work both.
It seems that the "no--sandbox" arg shouldn't affect to webkit

Thanks!

 


Thanks

**Comment by mxschmitt** [comment]
Sorry for the late response! Is the issue still persistent? The sandbox is now by default disabled.
