### ISSUE TITLE
Run tests with multiple sets of configurations

### ISSUE THREAD

**Issue by Sreejithw** [playwright-community/jest-playwright#240]
I have same sets of JSON data with configurations (TestID,Browser Type, Device Type, Url etc. ). Is there a way i can use jest-playwright to run a single test with different configurations?

**Comment by mmarkelov** [comment]
@Sreejithw I'm not that it will be able. As workaround you can split it in multiple configs and use `JEST_PLAYWRIGHT_CONFIG`, like so:

```js
// jest-playwright.config1.js
module.exports = {
    launchOptions: {
        args: ['--no-sandbox', '--disable-dev-shm-usage'],
    },
    contextOptions: {
        ignoreHTTPSErrors: true
    },
    browsers: ['chromium'],
    devices: ['iPhone 8']
}


// jest-playwright.config2.js
module.exports = {
    browsers: ['firefox'],
    devices: ['iPhone 8']
}
```

`"test1": "JEST_PLAYWRIGHT_CONFIG='jest-playwright.config1.js'"`
`"test2": "JEST_PLAYWRIGHT_CONFIG='jest-playwright.config2.js'"`

**Comment by singularitypress** [comment]
@mmarkelov Where would we place this? (I apologize if I missed this in the docs but I didn't see anything like this):
"test1": "JEST_PLAYWRIGHT_CONFIG='jest-playwright.config1.js'"
"test2": "JEST_PLAYWRIGHT_CONFIG='jest-playwright.config2.js'"

**Comment by mmarkelov** [comment]
@singularitypress this is scripts for running your tests. `JEST_PLAYWRIGHT_CONFIG` is environment variable for define special `jest-playwright` config file. You can place it to your **package.json** in scripts section:
```js
// package.json
{
...
  "scripts": {
    ...
    "test1": "JEST_PLAYWRIGHT_CONFIG='jest-playwright.config1.js'",
    "test2": "JEST_PLAYWRIGHT_CONFIG='jest-playwright.config2.js'"
  }
}
```
