### ISSUE TITLE
Skip Option missing npm package type declaration

### ISSUE THREAD

**Issue by committedtester** [playwright-community/jest-playwright#242]
Typescript compiling of a package that uses the jest-playwright-preset will error with 
node_modules/jest-playwright-preset/types/global.d.ts:2:33 - error TS2307: Cannot find module '../src/types' or its corresponding type declarations.
2 import type { SkipOption } from '../src/types'

To reproduce, download 
https://github.com/playwright-community/playwright-jest-examples/tree/master/basic-ts
In a terminal run tsc

 - MacOS
 - Playwright version [e.g. 1.2.1]
 - jest-playwright version [e.g. 1.2.1]
(see package.json in github for more)
 - node v14.4.0

```js
module.exports = {
  verbose: true,
  preset: 'jest-playwright-preset',
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
}
```

??? Potential to be fixed by 
https://github.com/playwright-community/jest-playwright/pull/241/commits/a6c8694c5e2a63bd36a41a43d006d16beffdb07a

**Comment by mmarkelov** [comment]
@committedtester thanks for your report. This is already fixed in new release. So you can use **jest-playwright-preset@next**. The next stable release will be published soon

**Comment by aaron-mckay-ncino** [comment]
You guys are doing a great job! Looking forward to the next release
Just letting you know that you've also got these errors on "jest-playwright-preset": "^1.3.0-rc10",

Interface 'JestPlaywrightContext' incorrectly extends interface 'Context'.
  The types of 'config.displayName' are incompatible between these types.
    Type 'string | { name: string; color: Color; } | undefined' is not assignable to type 'DisplayName | undefined'.
      Type 'string' is not assignable to type 'DisplayName | undefined'.
and

Interface 'JestPlaywrightTest' incorrectly extends interface 'Test'.
  The types of 'context.config' are incompatible between these types.
    Type 'JestPlaywrightProjectConfig' is not assignable to type 'ProjectConfig'.

**Comment by mmarkelov** [comment]
@aaron-mckay-ncino can you check out the latest version? Otherwise it can be some problems with **node_modules** maybe
