### ISSUE TITLE
ignoreHTTPSErrors flag

### ISSUE THREAD

**Issue by mslowiak** [playwright-community/jest-playwright#247]
**Is your feature request related to a problem? Please describe.**
I wanted to omit the `ERR_CERT_AUTHORITY_INVALID` error:

```
net::ERR_CERT_AUTHORITY_INVALID at <URL>
    ====================== page.goto logs ======================
    [api] navigating to <URL>, waiting until "load"
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

**Describe the solution you'd like**
Would be great to support `ignoreHTTPSErrors` somehow in `jest-playwright.config.js` or maybe it is supported but I got no idea how to use that.

**Comment by mxschmitt** [comment]
Hi,

you can use such a config (`jest-playwright.config.js`) to add the ignoreHTTPSErrors flag:

```js
module.exports = {
  contextOptions: {
    ignoreHTTPSErrors: true
  }
}

```
