### ISSUE TITLE
Error when using custom selector engine: selector engine has been already registered

### ISSUE THREAD

**Issue by Maksandre** [playwright-community/jest-playwright#250]
My issue looks pretty similar to this one - https://github.com/playwright-community/jest-playwright/issues/99
I'm trying to use custom selector engine from this [example](https://github.com/microsoft/playwright/blob/master/docs/extensibility.md#custom-selector-engines) in my jest-playwright.config.js file like this:

**jest-playwright.config.js**
 ```js
const { createTagNameEngine } = require("./tests/engine");

module.exports = {
  browsers: ["chromium"],
  launchOptions: {
    headless: true
  },
  selectors: [
    {name: 'tag', script: createTagNameEngine}
  ]
}
```

and I get an error when running tests:

```
Test suite failed to run
"tag" selector engine has been already registered
```

 - OS: Windows
 - Playwright version 1.2.1
 - jest-playwright version 1.2.1

**jest.config.js**

 ```js
module.exports = {
  preset: 'jest-playwright-preset'
}
```

I also created this simple example to explain my problem.
https://github.com/Maksandre/jest-playwright-engine

How it looks in the console
![image](https://user-images.githubusercontent.com/23031938/88474532-d2d12580-cf40-11ea-8f42-4a2a584e139f.png)

I'm using 4 test suites there. If you remove any of them everything will work fine.

**Comment by mxschmitt** [comment]
Hi, thanks for filing an issue, I was able to reproduce it. Fix will be provides shortly.
