### ISSUE TITLE
Screenshot is being created but it's blank, on test failure 

### ISSUE THREAD

**Issue by ajaykhobragade** [playwright-community/jest-playwright#253]
I am following the steps as per the recommendation "**Usage with jest-circus"** for taking screenshot on test failure, it works fine as long as screenshot being created but i see screenshot is white blank page, i was suspecting if it's taking too early while page is still loading so tried on different pages & manually as well, but it seems it captures white blank every time. I attached all my config files here for reference.
[Archive.zip](https://github.com/playwright-community/jest-playwright/files/4982533/Archive.zip)

Am i missing anything or doing anything wrong? Quick response would be helpful. Thanks.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 
 - Playwright version [e.g. 1.2.1]
 - jest-playwright version [e.g. 0.2.3]

**Comment by mmarkelov** [comment]
@ajaykhobragade I just tried it with `jest-playwright@0.2.3` and with `jest-playwright@1.3.0` it works fine for me. I'm not sure but may be if you running your tests with server, it cause this kind of issue. If you are using server option to start your test, I can check it out

**Comment by mmarkelov** [comment]
Also tried it with [cra example](https://github.com/playwright-community/playwright-jest-examples/tree/master/create-react-app). Seems to be ok

**Comment by ajaykhobragade** [comment]
@mmarkelov , Thanks for reply. I think you were correct, it was something to do with script, i tried couple of things not sure what fixed but my guess is either i was taking screenshot of page Vs browser or using playwright strictly Vs jest-playwright format but it seems to be working fine now.

Also, wondering if you have any recommendations around auto creating log along with screenshot on test failure?
Thanks in advance

**Comment by ajaykhobragade** [comment]
@mmarkelov , did you get a chance to look at this below?

Also, wondering if you have any recommendations around auto creating log along with screenshot on test failure?

**Comment by mmarkelov** [comment]
@ajaykhobragade unfortunately I didn't get much time for a while. But I don't have any recommendations for it. I suppose you can use custom environment:
```js
const PlaywrightEnvironment = require('jest-playwright-preset/lib/PlaywrightEnvironment')
  .default

class CustomEnvironment extends PlaywrightEnvironment {
  async setup() {
    await super.setup()
    // Your setup
  }

  async teardown() {
    // Your teardown
    await super.teardown()
  }

  async handleTestEvent(event) {
    if (event.name === 'test_done' && event.test.errors.length > 0) {
      const parentName = event.test.parent.name.replace(/\W/g, '-')
      const specName = event.test.name.replace(/\W/g, '-')

      await this.global.page.screenshot({
        path: `screenshots/${parentName}_${specName}.png`,
      })
    }
  }
}

module.exports = CustomEnvironment
```

But I suppose we can think about some extra option to make screenshots underhood. I need to check it out

**Comment by ajaykhobragade** [comment]
Ok, will forward to it.
Thanks.
