### ISSUE TITLE
Allow running same tests against multiple browsers parallelly 

### ISSUE THREAD

**Issue by tanvee38** [playwright-community/jest-playwright#257]
Thanks for the amazing test framework! I have some end-to-end tests using playwright and I am using jest as the test runner. I want to run the same tests against Chrome, Firefox and Safari parallelly where the tests within a test file should run sequentially. Kindly let me know if I can do it with jest-playwright? Or if no, is there a way I can achieve it. Testing an application for cross-browser compatibility is very valuable, and jest-playwright could make it much simpler.  Kindly let me know your suggestions.Thanks in advance!

**Comment by pavanreddy61** [comment]
U can see in readme that u can define browsers u want to run the tests in jest-playwright config file. And jest playwright will take care of running it on those browsers parallely and within a test file the tests should run sequentially.

**Comment by mmarkelov** [comment]
@tanvee38 thank you! Unfortunately you can't run same tests for multiple browsers in parallel. I just made some research on it, but the solution is very unstable. So for a now there is no plans to support this feature. Maybe I'll put this solution in separate package. But for now I just don't have enough time to do it.

**Comment by tanvee38** [comment]
@mmarkelov thanks a lot for your response! Kindly let me know if you can think of any workaround I can use for this.

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

It provides horizontal and vertical parallelisation. Also on the test level: https://playwright.dev/docs/test-parallel
