### ISSUE TITLE
Tracking the coverage create empty table for index.html

### ISSUE THREAD

**Issue by ajaykhobragade** [playwright-community/jest-playwright#267]
Hi, I am following steps mentioned under "**Tracking the coverage**", I got nyc, babel-istanbul installed, updates the jest-playwright.config.js and all other required config files. I could able to run sample test and see the coverage folder with index.html gets created but what i see is the html has empty table. I intentionally make my test fail so i could see the coverage.

I attached all my config files here for reference, wondering if i missing anything and messing it up by installing too many unnecessary\duplicate things. 

I also see error message below after execution>>
Thanks in advance.
```js
// .babelrc
{
    "env": {
      "test": {
        "plugins": [ "istanbul" ]
      }
    }
  }
```

_Ran all test suites.
[Archive.zip](https://github.com/playwright-community/jest-playwright/files/5009013/Archive.zip)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khobraj/.npm/_logs/2020-07-31T20_12_16_013Z-debug.log
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ coverage: `nyc npm run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khobraj/.npm/_logs/2020-07-31T20_12_16_118Z-debug.log_

**Comment by mmarkelov** [comment]
@ajaykhobragade I just don't have much experience with **coverage**, @mxschmitt could you please check it out?

**Comment by mxschmitt** [comment]
Hi sorry for the late response. What kind of build system are you using for the your client side code?
I you haven't seen, we have a full working example located here: https://github.com/playwright-community/playwright-jest-examples/tree/master/create-react-app-coverage

**Comment by ajaykhobragade** [comment]
@mxschmitt , I have Node JS testing web browser using with Jest-playwright, expect-playwright, babel-plugin-istanbul, nyc.
 Am i missing anything here? Do you have working example for that?

**Comment by mxschmitt** [comment]
> @mxschmitt , I have Node JS testing web browser using with Jest-playwright, expect-playwright, babel-plugin-istanbul, nyc.
> Am i missing anything here? Do you have working example for that?

You need to integrate `babel-plugin-istanbul` into your build system with Babel. That means your local buildserver needs to use it while testing.

You can check if its correctly configured if `window.__coverage__` is defined in your Chrome DevTools for example.

**Comment by ajaykhobragade** [comment]
@mxschmitt , Thanks for all the help, i think my build correctly integrate with Babel, what i missing is to see a good example of Jest-Playwright test coverage option that supports Javascript, Node JS just like what you have for Typescript link above.

Let me know if you guys come up with something like that because currently there is enough information around how to add coverage through different ways but just not good enough that will support Javascript.

Thanks again.

**Comment by ajaykhobragade** [comment]
@mxschmitt , okay to close ticket unless there is anything more to add.
