### ISSUE TITLE
[QUESTION] How to allow multiple file downloads?

### ISSUE THREAD

**Issue by ok-AK** [playwright-community/jest-playwright#269]
Hello,
When using Chrome and attempting to download multiple files at the same time. Chrome displays a notification saying, "Localhost wants to Download multiple files - Allow/Block".

![Download Multiple Files - Allow Block](https://user-images.githubusercontent.com/17037706/88982387-fcf65080-d27c-11ea-9cfb-42d869c94cc1.png)

I use a jest-playwright.config.js file to set browser context options. I have the following in my config file and I can successfully test cases involving single file downloads.

### jest-playwright.config.js
```module.exports =
{
    launchOptions:
    {
		headless: false,
	},
	contextOptions:
	{
		acceptDownloads: true
	},
	browsers: ["chromium"]//, "firefox", "webkit"]
};
```

Is there a setting or flag I can use to either make the notifications always allow or a download specific setting that will automatically allow multiple files to download? Thanks!

**Comment by mmarkelov** [comment]
@ok-AK seems like that related to `playwright`. I can try to find solution, when I'll have some free time
