### ISSUE TITLE
[Discussion] Move jest-process-manager options in separate file

### ISSUE THREAD

**Issue by mmarkelov** [playwright-community/jest-playwright#295]
Just noticed that there is problem with passing options to `jest-process-manager` if `jest-playwright.config` doesn't exist in root directory:

https://github.com/playwright-community/jest-playwright/blob/6d1c3d1d538692207ca390caa13eb4a1be1fafec/src/global.ts#L29-L30

I just look throw `jest` and find out [this issue](https://github.com/facebook/jest/issues/9263) - so there is no way to get test config and get the right path to config file.

So I think about moving `jest-process-manager` configuration to separated file. That should be always locate in **jestRoot** directory.

**Comment by maneetgoyal** [comment]
The [docs](https://github.com/playwright-community/jest-playwright#configuration) mentions that we can use:

```
module.exports = {
  preset: 'jest-playwright-preset',
  testEnvironmentOptions: {
    'jest-playwright': {
      // Options...
    },
  },
}
```

But when I use this format to produce something like the following:

```
module.exports = {
  preset: 'jest-playwright-preset',
  testEnvironmentOptions: {
    'jest-playwright': {
      serverOptions: {
        command: "yarn start",
        port: 6006,
        debug: true,
        launchTimeout: 30000,
      },
    },
  },
}
```

then the `serverOptions` are getting ignored. Does my issue seem related to this #295?

When I create a separate `jest-playwright.config.js`, everything works as expected.

**Comment by mmarkelov** [comment]
@maneetgoyal I don't think so. Could you open a separate issue?

**Comment by maneetgoyal** [comment]
Sure, here it is: https://github.com/playwright-community/jest-playwright/issues/446.
