### ISSUE TITLE
How to connect to browser grid? `wsEndpoint` in `connectOptions` doesn't work

### ISSUE THREAD

**Issue by aha-oretama** [playwright-community/jest-playwright#358]
**Describe the bug**
In #90 , `connectBrowserApp` (it's renamed to `connectOptions`) was introduced in order to connect to browser grid.
However, I cannot connect to existing browser grid by setting it.

**To Reproduce**
I'm using [moon](https://aerokube.com/moon/latest/). Moon provides browser grids.
I already confirmed that original playwright can access it like this code.

```js
const playwright = require('playwright');

(async () => {
  var browser = await playwright.chromium.connect({ timeout: 0, wsEndpoint: 'ws://{HOST}:4444/playwright/chromium' });
  const page = await browser.newPage();
  await page.goto('https://aerokube.com/moon/');
  await page.screenshot({ path: `screenshot.png` });
  await browser.close();
})();
```

With jest-playwright, I tried if the tests can running in the browser grid or not with `jest-playwright.config.js`. But it didn't connect to the browser grid and it ran in the local browser. 

```
module.exports = {
  launchType: 'SERVER',
  connectOptions: {
    timeout: 0,
    wsEndpoint: 'ws://{HOST}:4444/playwright/chromium'
  },
  browsers: [
    'chromium',
  ],
};
```

**Expected behavior**
When `wsEndpoint` in `connectOptions` was passed, the tests should be executed in the browser grid whose url is written in `wsEndpoint` .

**Desktop (please complete the following information):**
 - OS: macOS (locally), moon: 1.6.1
 - Playwright version : 1.3.0
 - jest-playwright version : 1.3.1

**Additional context**

In my investigation, `launchType` seems to be set `SERVER` from these codes. 
https://github.com/playwright-community/jest-playwright/blob/948fda516bbaf4e69683d1fa20f2f09909ccdc8d/src/PlaywrightEnvironment.ts#L75-L76

However, it seems that this code will launch the local browser... , not connect the existing browser...
https://github.com/playwright-community/jest-playwright/blob/948fda516bbaf4e69683d1fa20f2f09909ccdc8d/src/PlaywrightRunner.ts#L95-L101

**Comment by mmarkelov** [comment]
@aha-oretama thank you for your report! I will take a look.
