### ISSUE TITLE
jestPlaywrightSkip isn't skipping tests

### ISSUE THREAD

**Issue by JohnPaulHarold** [playwright-community/jest-playwright#368]
**Describe the bug**

`jestPlaywrightSkip()` isn't skipping devices

**To Reproduce**

```js
// test
describe("jestPlaywrightSkip", () => {
    const config = { browsers: [], devices: ["iPhone 6", "Pixel 2"] };
    const specName = "Should only work on desktop";
    
    it.jestPlaywrightSkip(config, specName, async () => {
        expect(false).toBeFalsy();
    });
});
```

**Expected behavior**
I'd expect that only the "browser: chromium device: browser" test should run

**Screenshots**
<img width="719" alt="Screenshot 2020-09-24 at 15 27 10" src="https://user-images.githubusercontent.com/9934306/94158563-73c55980-fe7a-11ea-913d-583316e26c08.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6 
 - Playwright version 1.4.1
 - jest-playwright version v1.4.0-rc1

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

```js
module.exports = {
  preset: "jest-playwright-preset",
  transform: {
    "^.+\\.tsx?$": "ts-jest",
  },
  testMatch: ["**/e2e/**/*.spec.[jt]s?(x)", "**/*.spec.[jt]s?(x)"],
};

```

**Additional context**

my playwright config, if it helps

```js
const desktop = {
  name: "desktop",
  viewport: {
    width: 1280,
    height: 720,
  },
  userAgent:
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
  deviceScaleFactor: 1,
  isMobile: false,
  hasTouch: false,
};

module.exports = {
  browsers: ["chromium"],
  devices: ["iPhone 6", "Pixel 2", desktop],
  serverOptions: {
    command: `yarn start`,
    port: 3005,
    launchTimeout: 20000,
    debug: true,
  },
  launchOptions: {
    headless: true,
  },
  collectCoverage: false,
};
```

**Comment by mmarkelov** [comment]
@JohnPaulHarold you also need to define browser to skip:
https://github.com/playwright-community/jest-playwright/blob/cde452240eaa6d332d8bf291402ac51328c3a69a/src/utils.ts#L181-L196
So your test should be:
```js
// test
describe("jestPlaywrightSkip", () => {
    const config = { browsers: ["chromium"], devices: ["iPhone 6", "Pixel 2"] };
    const specName = "Should only work on desktop";
    
    it.jestPlaywrightSkip(config, specName, async () => {
        expect(false).toBeFalsy();
    });
});
```

**Comment by JohnPaulHarold** [comment]
OK. My assumption was that choosing to skip no browsers `browsers: []` would do just that and my example would just skip the devices specified.

If you want to run browser/desktop only tests, is creating a  "desktop" device and then using the above the way to go?

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

The official test-runner provides conditional skips out of the box see here: https://playwright.dev/docs/test-annotations#skip-a-test
