### ISSUE TITLE
[Question] Can you share a browser context between different test files?

### ISSUE THREAD

**Issue by kronkake** [playwright-community/jest-playwright#379]
Hi!

I'm working on E2E testing a site which is hidden behind a login. This means logging in and out between each test often fails as the server runs out of sessions. Is it possible to seperate tests by files, but still share the same browsercontext/tab while running --runInBand? Or does it exist a better solution I've not considered?

**Comment by jgibson02** [comment]
I'm in a similar scenario, trying to authenticate with the application before all test suites and then use separate pages within the same browser context for each suite in parallel. Tried to use a custom Jest environment similar to what's described in the "Usage with jest-circus" section of the readme but have not been able to figure out how to share the same context.
