### ISSUE TITLE
page is not defined

### ISSUE THREAD

**Issue by FezVrasta** [playwright-community/jest-playwright#4]
Hi, I'm on jest@25.1.0, when I add your preset and attempt to reference `page` I get:

```
    ReferenceError: page is not defined
```

Do I need any additional configuration in addition to the one in the readme?

I tried to use `browser.newPage()` but it tells me `browser is not defined`

**Comment by mmarkelov** [comment]
@FezVrasta I just made [repo](https://github.com/mmarkelov/jest-playwright-preset-example) for example configuration. I suppose you need to define jest preset.
- You can add it to your `package.json`:
```json
  "jest": {
    "preset": "jest-playwright-preset"
  },
``` 
- Or you can do it with `jest.config.js` file:
```javascript
module.exports = {
    preset: "jest-playwright-preset"
}
```

I suppose it should be placed in README

**Comment by FezVrasta** [comment]
That's what I have done.

If I manually apply the `globalSetup`, `globalTeardown` and `testEnvironment` Jest configuration properties it works though...

**Comment by mmarkelov** [comment]
@FezVrasta it's difficult to say what is going wrong without whole configuration. I can only suppose that some of other options can override `jest-playwright-preset`. I'll try to dive into this issue to search possible problems.

**Comment by FezVrasta** [comment]
This is the whole repository, I'm trying to migrate from Puppeteer to Playwright:

https://github.com/popperjs/popper-core/tree/test/playwright

You can find the Jest configuration in the `.config` folder.

**Comment by mmarkelov** [comment]
@FezVrasta thank you!

**Comment by mmarkelov** [comment]
@FezVrasta I suppose this is because you define **testEnvironment**:
https://github.com/popperjs/popper-core/blob/fe24beeb92da1bb9573d2e6929940220008c263b/.config/jest.config.js#L6

And `jest-playwright-preset` like `jest-puppeteer` use it under hood. 

I think this info should be added in README

**Comment by FezVrasta** [comment]
No that's not it, you can safely remove `testEnvironment` `globalSetup` and `globalTeardown` and add back `preset` and you will still reproduce the issue.

**Comment by criles25** [comment]
for others that stumble upon this issue... i had to comment out

```
testEnvironment: "node",  // comment this line out
```

the `jest --init` created this setting by default for the `jest.config.js` it generated.
