### ISSUE TITLE
Using a custom environment per the docs give: "TypeError: Cannot destructure property 'collectCoverage' of 'this._jestPlaywrightConfig' as it is undefined."

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#413]
**Describe the bug**
Using a custom environment per the docs give: `TypeError: Cannot destructure property 'collectCoverage' of 'this._jestPlaywrightConfig' as it is undefined.` The custom environment has been configured according to https://github.com/playwright-community/jest-playwright#usage-with-jest-circus

**To Reproduce**
Add a custom environment according to https://github.com/playwright-community/jest-playwright#usage-with-jest-circus

**Expected behavior**
It should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Playwright version: 1.5.1
 - jest-playwright version: 1.3.1

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
module.exports = {
  // Test sequencers cannot exist in projects, only in global config
  testSequencer: './tests/e2e/util/jestSequencer.js',
  projects: [
    {
      displayName: 'E2E',
      rootDir: 'tests/e2e',
      testEnvironment: '<rootDir>/util/CustomEnvironment.js',
      testRunner: 'jest-circus/runner',
      runner: '<rootDir>/util/serialJestRunner.js',
      preset: 'jest-playwright-preset',
      globals: {
        TEST_URL: testUrl,
      },
      setupFilesAfterEnv: ['<rootDir>/jest.setup.js', 'expect-playwright'],
      globalSetup: '<rootDir>/util/globalSetup.js',
      globalTeardown: '<rootDir>/util/globalTeardown.js',
    },
  ],
};
```

**Additional context**
This is the custom environment:

```js
class CustomEnvironment extends PlaywrightEnvironment {
  constructor(config) {
    super(config);
    this.config = config;
  }

  async setup() {
    await super.setup();
    this.allure = new Allure();
    this.allure.setOptions({
      targetDir: `${this.config.rootDir}/allure_results`,
    });
  }

  async handleTestEvent(event) {
    switch (event.name) {
      case 'start_describe_definition':
        this.allure.startSuite(event.blockName);
        break;

      case 'test_start':
        this.allure.startCase(event.test.name);
        break;

      case 'test_done': {
        if (event.test.errors.length > 0) {
          const screenshot = await this.global.page.screenshot();
          this.allure.addAttachment('screenshot', screenshot, 'image/png');
          this.allure.endCase('failed', event.error);
        } else this.allure.endCase('passed');
        break;
      }

      case 'run_finish': {
        this.allure.endSuite();
        break;
      }

      default:
        break;
    }
  }
}
```

**Comment by mmarkelov** [comment]
@thernstig looks strange. I just run it with this env:
```js
const PlaywrightEnvironment = require('jest-playwright-preset/lib/PlaywrightEnvironment')
	.default

class CustomEnvironment extends PlaywrightEnvironment {
	constructor(config) {
		super(config);
		this.config = config;
	}

	async setup() {
		await super.setup();
	}

	async teardown() {
		// Your teardown
		await super.teardown()
	}
}

module.exports = CustomEnvironment

```

I just think that there is some trouble with `teardown` method. @mxschmitt maybe you have any thoughts with it?

**Comment by thernstig** [comment]
I'll try to add this piece of code:

```js
async teardown() {
		// Your teardown
		await super.teardown()
	}
```

But I don't think that should matter, as it should call the `super.teardown()` automatically if I do not specify it myself.

I do use a file called jest-playwright.config.js as well, if that is of any help:

```js
const { browser, slowMo } = require('./util/environmentSetup');

module.exports = {
  launchOptions: {
    headless: process.env.TEST_HEADLESS !== 'false',
    slowMo,
  },
  contextOptions: {
    ignoreHTTPSErrors: true,
    acceptDownloads: true,
  },
  browser,
};
```

**Comment by thernstig** [comment]
It is because of this line `const { wsEndpoint, browserName, testEnvironmentOptions } = this._config;` where you expect the config to come from the Jest config's testEnvironmentOptions, which was a new feature you added.

But this broke specifying the config via jest-playwright.config.jest in the root dir of the project.

**Comment by thernstig** [comment]
I added it in jest.config.js according to https://github.com/playwright-community/jest-playwright#configuration and now it passes that step. It does not fail on `TypeError: Cannot destructure property 'collectCoverage' of 'this._jestPlaywrightConfig' as it is undefined.` anymore.

But it then instead fails on this:

```sh
  ● Test suite failed to run

    TypeError: Cannot read property 'logger' of undefined

      12 |
      13 |   async setup() {
    > 14 |     await super.setup();
         |                 ^
      15 |     console.log(this._jestPlaywrightConfig);
      16 |     this.allure = new Allure();
      17 |     this.allure.setOptions({

      at BrowserType.connect (../../node_modules/playwright/lib/client/browserType.js:96:32)
      at getBrowserPerProcess (../../node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:32:31)
      at CustomEnvironment.setup (../../node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:87:44)
      at CustomEnvironment.setup (util/CustomEnvironment.js:14:17)
```

**Comment by mmarkelov** [comment]
@thernstig I just look through your `jest.config.js` and noticed that you are using custom `runner`:
```js
runner: '<rootDir>/util/serialJestRunner.js',
```

There is some configuration that passed throw `jest-playwright` `runner` to `testEnvironment`.

I didn't test it with custom `runner` so I need some time to figure how to handle this case

**Comment by thernstig** [comment]
It just looks like this:

```js
class SerialJestRunner extends DefaultJestRunner {
  constructor(...args) {
    super(...args);
    this.isSerial = true;
  }
}
````

**Comment by mmarkelov** [comment]
@thernstig you can try to extend your runner from `jest-playwright`:
```js
const PlaywrightRunner = require('jest-playwright-preset/lib/PlaywrightRunner')
	.default

class SerialJestRunner extends PlaywrightRunner {
	constructor(...args) {
		super(...args);
		this.isSerial = true;
	}
}

module.exports = SerialJestRunner
```

**Comment by thernstig** [comment]
That made it, thanks! Maybe there should be a note about this in the README?

**Comment by mmarkelov** [comment]
@thernstig yeah! That make sense. I put it [here](https://github.com/playwright-community/jest-playwright#usage-with-custom-runner)
