### ISSUE TITLE
[Question] MaxListenersExceededWarning?

### ISSUE THREAD

**Issue by NareshMurthy** [playwright-community/jest-playwright#437]
I have been getting this warning when I run a describe which has more number of tests inside, is there a way to fix this warning?
`(node:46) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnected listeners added to [FFBrowser]. Use emitter.setMaxListeners() to increase limit`

This is the version I am running on.
```
"jest": "^26.6.1",
 "jest-playwright-preset": "^1.4.0-rc2",
 "playwright": "1.5.1"
```

**Comment by mxschmitt** [comment]
Hi, could you try to upgrade to playwright 1.5.2? There are probably related fixes in the changelog: https://github.com/microsoft/playwright/releases/tag/v1.5.2

**Comment by NareshMurthy** [comment]
It looks like they have enabled the warning for safety reasons in the recent update https://github.com/microsoft/playwright/pull/4223

Thanks @mxschmitt
