### ISSUE TITLE
Ability to specify different wsEndpoints for each browser

### ISSUE THREAD

**Issue by pjcalvo** [playwright-community/jest-playwright#443]
**Is your feature request related to a problem? Please describe.**
I am setting up a ws proxy server to start remote environments on demand. But I need a way to specify which browser is starting the connection in order to be able to programatically spin the server.

**Describe the solution you'd like**
Would be nice to be able to specify different servers for each browser type.

```javascript
browsers: [
   {name:'chromiun', wsEndpoint : 'ws://chrome.proxy.com:4444'},
   {name:'firefox', wsEndpoint : 'ws://firefox.proxy.com:4444'}
]
...
```

**Describe alternatives you've considered**
The alternative will be to start the browser and context inside the tes and skip the initial setup.

**Comment by mmarkelov** [comment]
@pjcalvo I believe that you are able to do something like this:
```js
// jest-playwright.config.js
module.exports = {
	connectOptions: {
		chromium: {
			wsEndpoint: 'ws://chrome.proxy.com:4444'
		},
		firefox: {
			wsEndpoint: 'ws://firefox.proxy.com:4444'
		}
	},
       ...
}
```

**Comment by pjcalvo** [comment]
THanks. I didn't know that was possible.
