### ISSUE TITLE
serverOptions are getting ignored

### ISSUE THREAD

**Issue by maneetgoyal** [playwright-community/jest-playwright#446]
The [docs](https://github.com/playwright-community/jest-playwright#configuration) mentions that we can use:

```js
module.exports = {
  preset: 'jest-playwright-preset',
  testEnvironmentOptions: {
    'jest-playwright': {
      // Options...
    },
  },
}
```

But when I use this format to produce something like the following:

```js
module.exports = {
  preset: 'jest-playwright-preset',
  testEnvironmentOptions: {
    'jest-playwright': {
      serverOptions: {
        command: "yarn start",
        port: 6006,
        debug: true,
        launchTimeout: 30000,
      },
    },
  },
}
```

then the `serverOptions` are getting ignored.

When I create a separate `jest-playwright.config.js`, everything works as expected.

_Originally posted by @maneetgoyal in https://github.com/playwright-community/jest-playwright/issues/295#issuecomment-716931185_

**Comment by maneetgoyal** [comment]
cc @mmarkelov

**Comment by mmarkelov** [comment]
@maneetgoyal yeah! I just look through this. And unfortunately there is no way to get `testEnvironmentOptions` in **jest setup**, so for a while you should use  `jest-playwright.config.js`
