### ISSUE TITLE
[Question] jestPlaywrightSkip with describe.each?

### ISSUE THREAD

**Issue by NareshMurthy** [playwright-community/jest-playwright#447]
I have a describe each block similar to this

```js
describe.each`
  a    | b    | expected
  ${1} | ${1} | ${2}
`('$a + $b', ({a, b, expected}) => {
  test(`returns ${expected}`, () => {
    expect(a + b).toBe(expected);
  });
});
```

How do I attach the` jestPlaywrightSkip({ browsers: ['chromium'] })` to the describe block instead of mentioning in the each `it/test`?

**Comment by mmarkelov** [comment]
@NareshMurthy you can attach `jestPlaywrightSkip` to `describe` block like so:
```js
describe.jestPlaywrightSkip({browsers: ['chromium']}, 'Describe', () => {
  beforeAll(async () => {
     ...
  });

  it('test2', async () => {
    ...
  });
});
```

But I'm not sure that it will possible with `describe.each`

**Comment by mxschmitt** [comment]
Please reopen if the issue is still persistent.
