### ISSUE TITLE
[Question] How to implement error listener that polls for specific span

### ISSUE THREAD

**Issue by sjurgis** [playwright-community/jest-playwright#471]
I'm not sure where to post this question - jest or playwright repo, but I figured I'll start in the middle.

In a web app I'm testing (Salesforce) it's a common pattern to throw an error toast for errors you've caught or platform throws a different modal if some unhandled exception occurs. Basically there's nothing ever that just ends up in console.

I wan't to capture those so I could capture intermittent failures or something my suite wouldn't catch. I'd basically would need some poller that keeps checking DOM for these two spans/divs to appear and throw exception + take a screenshot. I'd also need a control mechanism to disable this for tests where I actually do expect some errors to be thrown.

Sorry if wrong repo as this question kinda generic.

**Comment by mmarkelov** [comment]
@sjurgis thank you for your question. I suppose that you will need to use some [custom environment](https://github.com/playwright-community/jest-playwright#usage-with-custom-testenvironment)
I'll try to find out possible ways and build small demo for this.

**Comment by mmarkelov** [comment]
@sjurgis I just tried to reproduce your test case. So I build tiny [sandbox](https://bn063.csb.app/). In this example you will get an error toast if you click **Hello World** button. And I just build small tests for this:
```js
// Using this helper to run after each tests if we got error toast
const checkErrorToast = async () => {
  // look through for toast
  const toast = await page.$('#toast');
  if (toast) {
    // make a screenshot if we find toast
    await page.screenshot({
      // this is used to get test name
      path: `screenshots/${expect.getState().currentTestName}.png`,
    })
  }
}

describe( 'Test', () => {
  beforeAll(async () => {
    // It will navigate all browsers to url
    await page.goto('https://bn063.csb.app/');
  });

  afterEach(async() => {
    await checkErrorToast()
  })

  it('test 1', async () => {
    expect(1+1).toBe(2)
  });

  it('test 2', async () => {
    await page.click('#button');
    expect(1+1).toBe(2)
  });
});
```

I just hope it will help you

**Comment by sjurgis** [comment]
Good starting point, will try implementing this. 
Best would be continuous poll, but I think this might cover a lot of cases.

**Comment by mxschmitt** [comment]
Please reopen if the issue is still persistent.
