### ISSUE TITLE
Tests don't run

### ISSUE THREAD

**Issue by asmyshlyaev177** [playwright-community/jest-playwright#477]
**Describe the bug**
Tests get discovered but just not running

**To Reproduce**
It works initially and after some time it stop working.

**Expected behavior**
Tests should run.

**Screenshots**
<img width="645" alt="Screen Shot 2563-11-30 at 14 27 50" src="https://user-images.githubusercontent.com/19854148/100580600-d3c3fa80-3318-11eb-8e3d-795a59ffd0ab.png">
<img width="562" alt="Screen Shot 2563-11-30 at 14 28 06" src="https://user-images.githubusercontent.com/19854148/100580605-d6beeb00-3318-11eb-9b4a-1474416b1325.png">

**Desktop (please complete the following information):**
 - OS: [macOS Catalina]
 - Playwright version [1.6.2]
 - jest-playwright version [1.4.1]

**Jest configuration (`jest.e2e.config.js`):**

 ```js
module.exports = {
  verbose: true,
  collectCoverage: false,
  preset: 'jest-playwright-preset',
  testMatch: ['<rootDir>/src/**/*.test.e2e.js'],
}
```

`jest-playwright.config.js`:
```js
module.exports = {
  collectCoverage: false,
  browsers: ['chromium', 'webkit'],
  launchOptions: {
    headless: !process.env.DEBUG,
  },
  useDefaultBrowserType: true,
}
```

Simple test file `playwright.test.e2e.js`
```js
test('test', async () => {
  await page.goto('http://localhost:3000/')

  await jestPlaywright.debug()
})
```

**Additional context**
I tried clear jest cache and run with `--no-cache`, tried remove `yarn.lock` and `node_modules`.
After it stopped can't make it work again.

Trying to run like this
`DEBUG=true npx jest -c jest.e2e.config.js` or `npx jest -c jest.e2e.config.js`

Main jest config
```js
module.exports = {
  verbose: true,
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}'],
  coverageReporters: ['text', 'html'],
  coverageDirectory: './coverage/',
  coveragePathIgnorePatterns: [
    'spec.js',
    'polyfills',
    'service-worker',
    'coverage',
    'cypress',
    'cypress-coverage',
  ],
  testMatch: ['<rootDir>/src/**/*.test.js'],
  transform: { '\\.js': ['babel-jest'] },
}
```

**Comment by asmyshlyaev177** [comment]
Figured this out - `useDefaultBrowserType` without devices cause this.

**Comment by mmarkelov** [comment]
@asmyshlyaev177 yeah! That's true. It's expect passed `devices` with this case. I suppose that I should add some information about it in documentation
