### ISSUE TITLE
Respect `jest-process-manager` launchOptions inside the subdirectory jest.config.js

### ISSUE THREAD

**Issue by ocavue** [playwright-community/jest-playwright#499]
**Is your feature request related to a problem? Please describe.**

According to [this comment](https://github.com/playwright-community/jest-playwright/blob/v1.4.2/src/global.ts#L29), `
jest-playwright` will ignore `serverOptions` in a sub-package jest configuration. This cause some inconvenience with monorepo.

I created a repository https://github.com/ocavue/jest-playwright-monorepo-example as an example to describe this issue as well as a playground for anyone who wants to fix this issue. There are two sub-packages: `my-subpackage-01` and `my-subpackage-02` in this repository. I can tell jest to start the dev server for `my-subpackage-01` by adding `serverOptions` inside the root `jest-playwright.config.js`. But I can't start the dev server for `my-subpackage-02` even I added relative command in `packages/my-subpackage-02/jest.my-subpackage-02.config.js`.

**Describe the solution you'd like**

Respect the `launchOptions` configuration inside `packages/my-subpackage-02/jest.my-subpackage-02.config.js`.

**Describe alternatives you've considered**

Allow multi jest-process-manager configurations inside  `launchOptions`, like something bellow.

```js
// jest-playwright.config.js
module.exports = {
    serverOptions: [
        {
            command: `yarn workspace my-subpackage-01 dev`,
            launchTimeout: 60 * 1000,
            debug: true,
            port: 3001,
            usedPortAction: "error",
        }, 
        {
            command: `yarn workspace my-subpackage-02 dev`,
            launchTimeout: 60 * 1000,
            debug: true,
            port: 3002,
            usedPortAction: "error",
        }
    ]
}
```

However, by doing this, I can not start the dev server for `my-subpackage-02` *only* when I run tests inside `my-subpackage-02`. This will bring some limitations like that I can't use the same port for both my packages.

**Additional context**

N/A

**Comment by ocavue** [comment]
I can try to implement this feature if I can give some specific modification ideas.

**Comment by mmarkelov** [comment]
@ocavue actually i didn't think about this kind of logic. So I don't have any thoughts on it. I just thought that I can move this kind of logic in some separate file, but I'm not sure that it will be fine.

**Comment by JipSterk** [comment]
@mmarkelov `jest-dev-server` which is the underlying server running [already accepts an array](https://github.com/playwright-community/jest-process-manager/blob/177c6fb427a5e33082da698e407f97154fbd747f/src/types.d.ts#L132)
i would suggest the type of [`JestPlaywrightConfig.serverOptions`](https://github.com/playwright-community/jest-playwright/blob/1c44352716b2667145183f18ba86dbe69afdf8df/types/global.d.ts#L216) should be changed to `serverOptions?: JestProcessManagerOptions | JestProcessManagerOptions[]`

**Comment by mmarkelov** [comment]
@JipSterk yeah! good catch! Agreed
