### ISSUE TITLE
Is there a way to set cookies before running tests?

### ISSUE THREAD

**Issue by petriichuk** [playwright-community/jest-playwright#529]
I can set them in my test like:

    it('title', async () => {
            await context.addCookies([{
                name: 'mycookieskey',
                value: 'mycookiesvalue',
                domain: 'domain.com',
                path: '/'
             }])
    })

but is it possible to set them in PlaywrightEnvironment.ts ?

**Comment by mxschmitt** [comment]
yes, you can use beforeEach or beforeAll since its Jest.

**Comment by petriichuk** [comment]
> yes, you can use beforeEach or beforeAll since its Jest.

sure, but I mean globally for all spec files

**Comment by petriichuk** [comment]
yes, @mxschmitt you are right, will add that to beforeAll, since there might be a test with different user or login page test. Thanks

**Comment by reed-sdet** [comment]
can we not use globalSetup.js ?
