### ISSUE TITLE
Setting BROWSER might break jest-playwright

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#531]
**Describe the bug**
When running playwright in a VS Code terminal when connected to an ssh remote, it fails. The problem might however be "bigger" than just VS Code.

**To Reproduce**
1. Connect to repository on an ssh remote with VS Code and try to run a playwright suite in the VS code terminal.

**Expected behavior**
For it to run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS or Windows] Ubuntu 20.04
 - Playwright version [e.g. 1.1.1] 1.6.2
 - jest-playwright version [e.g. 1.0.0] 1.3.1

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**
n/a

**Additional context**
This might be a problem when someone has set BROWSER for any other purpose on their VM. I don't think jest-playwright should look at this environment variable. Possibly you could look at PLAYWRIGHT_BROWSERS_PATH to get browser from there, but I am not sure that would work either.

**Comment by mmarkelov** [comment]
@thernstig thanks for report. I just thought about deprecation of set up `browser` and `device` through process environment and left only ability to do this only with `jest-playwright.config.js` file.

**Comment by thernstig** [comment]
I think it would be good. User can invent their own env vars (like we do ourselves) if they want to control things. I think that might be a better approach. Otherwise I am not sure how to solve this `BROWSER` problem we have now. Want to push a fix removing it?

**Comment by mmarkelov** [comment]
@thernstig it will be nice!
