### ISSUE TITLE
Issue with using Jasmine alongside jest-playwright

### ISSUE THREAD

**Issue by jevgenijusmarinuskinas** [playwright-community/jest-playwright#538]
Hello,

I was using Jasmine to add reporters and get name of a test with Puppeteer. After Playwright migration, it is no longer working. 

My jest.setup.js looks like this:

```
jasmine.getEnv().addReporter({
    specStarted: result => jasmine.currentTest = result,
    specDone: result => jasmine.currentTest = result,
    suiteStarted: result => jasmine.currentSuite = result,
    suiteDone: result => jasmine.currentSuite = result,
});
````

Whenever I try to execute some tests, I am getting an error:

````
   ReferenceError: jasmine is not defined

    > 1 | jasmine.getEnv().addReporter({
        | ^
      2 |     specStarted: result => jasmine.currentTest = result,
      3 |     specDone: result => jasmine.currentTest = result,
      4 |     suiteStarted: result => jasmine.currentSuite = result,

      at Object.<anonymous> (test-environment/jest.setup.js:1:1)
````

Is there any possible solution?

**Comment by hananmalka** [comment]
Try to add to your jest.config.js:
testRunner: "jasmine2"

This works for me.

**Comment by jevgenijusmarinuskinas** [comment]
> Try to add to your jest.config.js:
> testRunner: "jasmine2"
> 
> This works for me.

Are you able to get the name of the current test? For example,

`jasmine["currentTest"].fullName?`

I am getting undefined for this, after following your guidelines.

**Comment by hananmalka** [comment]
@jevgenijusmarinuskinas 
Adding this:
```
jasmine.getEnv().addReporter({
specStarted: (result) => (jasmine.currentTest = result),
specDone: (result) => (jasmine.currentTest = result)
});
```

Then you will be able to get test name by calling:
`const testName = jasmine.currentTest.description
`

Take a look at this [answer](https://github.com/jasmine/jasmine/issues/611#issuecomment-553098129)

**Comment by mxschmitt** [comment]
Thanks @hananmalka, please reopen if the issue is still persistent. Its not intended to use it in combination with Jasmine but we are open to add guides / documentation for it if it works already.

**Comment by mostor-v** [comment]
Hi @jevgenijusmarinuskinas, how did you solve this issue? After migration from puppeteer to playwright i have same issue
