### ISSUE TITLE
[Feature request] Running tests suites on multiples chromium browser with different executablePath

### ISSUE THREAD

**Issue by PaulRosset** [playwright-community/jest-playwright#539]
**Is your feature request related to a problem? Please describe.**

I would like to run tests in multiple similar environments.

For example, I would like to my test suite on Google Chrome thanks to the [`executablePath`](https://playwright.dev/docs/api/class-browsertype?_highlight=launch#browsertypelaunchoptions) but also on Chromium Edge with a new [`executablePath`](https://playwright.dev/docs/api/class-browsertype?_highlight=launch#browsertypelaunchoptions)

But I can't do that since it accepts only one instance of `chromium` based browser.

**Describe the solution you'd like**

Running the same test suites on multiple same types of browsers with a different `executablePath`.

**Comment by mmarkelov** [comment]
@PaulRosset got your point and i just need to think about this feature. Maybe `browsers` should an array of object instead of string.
```js
// jest-playwright.config
{
  ...
  browsers: [
    {
      browserType: 'chromium',
      // options here, like here
      launchOptions: {
        ...
        executablePath
     },
     'chromium'
  ]
}
```

**Comment by PaulRosset** [comment]
yes, I was also thinking about that in terms of API.

It would allow us to consider `firefox`, `webkit`, and `chromium` only as "base" browser and allow us to fully use the power of `executablePath`.

Looks promising!
