### ISSUE TITLE
[QUESTION] How to configure jest-playwright not to fail test in uncaught error occurs on a page during test execution

### ISSUE THREAD

**Issue by roman-ponomarenko** [playwright-community/jest-playwright#544]
[QUESTION] How to configure jest-playwright not to fail a test in uncaught error occurs on a page during test execution?

The test fails with the following error message:
 Sign in test › User is able to sign with username

    TypeError: Cannot read property 'apply' of undefined

      at https:/xxxxx.xxx.com/account:14:1697

**To Reproduce**
Run a test for a page with an uncaught error(s) that occurs

**Screenshot**
https://ibb.co/LzmyGVB

**Expected behavior**
A test should not fail if all steps are passed when  an uncaught error(s) occurs on a page
[](url)
 - OS: macOS 
 - Playwright version: 1.7.1
 - jest-playwright version: 1.4.4

 ```js
module.exports = {
    preset: 'jest-playwright-preset',
    setupFilesAfterEnv: ['expect-playwright'],
    testTimeout: 60000,
    testEnvironmentOptions: {
        'jest-playwright': {
            browsers: ["chromium"],
            launchOptions: {
                headless: false
            },
            contextOptions: {
                ignoreHTTPSErrors: true,
                bypassCSP: true,
            }
        }
    }
}
```

**Comment by mmarkelov** [comment]
@roman-ponomarenko there is **[exitOnPageError](https://github.com/playwright-community/jest-playwright#options)** option

**Comment by roman-ponomarenko** [comment]
@mmarkelov that exactly what I was looking for, thanks a lot!
