### ISSUE TITLE
make `collectCoverage` optional

### ISSUE THREAD

**Issue by peterblazejewicz** [playwright-community/jest-playwright#564]
**Describe the bug**
The `collectCoverage` option on preset configuration is defined as required in preset types:
https://github.com/playwright-community/jest-playwright/blob/master/types/global.d.ts#L218

The Jest option definition make this optional by default (`false` by default).
So when using preset configuration that way (taken from ts sample):

```ts
import type { JestPlaywrightConfig } from "jest-playwright-preset";

const config: JestPlaywrightConfig = {
  browsers: ["chromium"],
  exitOnPageError: false,
  launchOptions: {
    headless: true,
  },
};
```

it reports error complaining about `collectCoverage` option.
Fix is easy, use `Partial<...>`, but IMO this should follow `jest` conventions.

Should this one be optional? Or should entire preset config should be make all-optional? Just like `jest` one.

```json
"jest": "^26.6.3",
"jest-playwright-preset": "^1.4.5",
"playwright": "^1.8.0",
```

thx!

**Comment by mmarkelov** [comment]
@peterblazejewicz thanks for report! I'll take a look

**Comment by mxschmitt** [comment]
@peterblazejewicz I'm curious how you do it, since jest-playwright reads the jest-playwright.config.js and no TypeScript file. do you use TSC to transcompile your TS config file into JS?

**Comment by peterblazejewicz** [comment]
Oh, no, I'm using `ts-jest` with `ts-node` option (so by the book):
https://jestjs.io/docs/en/configuration
No transpilation involved, e.g `basic-ts` can be rewritten to by all `.ts` based.

**Comment by peterblazejewicz** [comment]
> since jest-playwright reads the jest-playwright.config.js and no TypeScript file.

I've just realised what you've asked, sorry. Yes, you're correct, it won't work with `.ts` extension. Anyway,
one can reference types for @typedef/@type:

```js
// @ts-check
/**
 * @typedef {import('jest-playwright-preset').JestPlaywrightConfig} Config
 */

/** @type {Config} */
const config = {
    browsers: ["chromium"],
    exitOnPageError: false,
    launchOptions: {
        headless: false,
    },
    contextOptions: {
        storageState: "./auth.json",
    },
};

module.exports = config;
```
due to @ts-check, it won't pass compiler check.
