### ISSUE TITLE
Videos recorded are corrupt or poor quality in certain scenarios

### ISSUE THREAD

**Issue by russellg** [playwright-community/jest-playwright#566]
**Describe the bug**
When using certain devices or browsers, the video is corrupt or recorded poorly and with no color.

**To Reproduce**
This is the jest-config.js I am currently using:

 ```js
module.exports = {
  preset: "jest-playwright-preset",
  testEnvironmentOptions: {
    "jest-playwright": {
      contextOptions: {
        recordVideo: { dir: "video/" },
      },
      devices: [
        "Pixel 2 XL landscape",
        {
          name: "Desktop",
          deviceScaleFactor: 1,
          isMobile: false,
          hasTouch: false,
          defaultBrowserType: "firefox",
        },

        {
          name: "Desktop",
          deviceScaleFactor: 1,
          isMobile: false,
          hasTouch: false,
          defaultBrowserType: "webkit",
        },
        {
          name: "Desktop",
          deviceScaleFactor: 1,
          isMobile: false,
          hasTouch: false,
          defaultBrowserType: "chromium",
        },
      ],
      useDefaultBrowserType: true,
      launchOptions: {
        headless: false,
      },
    },
  },
};

```

**Expected behavior**
The video for each device should be created and recorded correctly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Playwright version: 1.80
 - jest-playwright: 1.45

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**
See above

**Additional context**
Seems to affect Pixel 2 XL landscape and Firefox browser configurations. Webkit and Chrome is fine.

Pixel 2 XL landscape: corrupted WEBM file.
Firefox: no color. yellow transparent bar running down page.

Please advise if this is already a known issue or needs to go upstream.

**Comment by mmarkelov** [comment]
@russellg I'm not sure that it is related to `jest-playwright`. I just tried to record a video for `Pixel 2 XL landscape` and also got an error, but I haven't got any problems with `firefox`
```js
(async () => {
	const pixel = devices["Pixel 2 XL landscape"];
	const browser = await chromium.launch();
	const context = await browser.newContext({ recordVideo: { dir: 'videos/' }, ...pixel });
	const page = await context.newPage();
	await page.goto('https://google.com/');
	await page.waitForTimeout(3000);
	await browser.close();
})();
```

@mxschmitt what do you think? Can it be related to `jest-playwright`?

**Comment by russellg** [comment]
These are my current dependencies from package.json:

**Comment by russellg** [comment]
As I am unsure if jest-playwright is the issue here, I think it's fair to close this this.
