### ISSUE TITLE
Run Multiple instances of chromium with different executablePath

### ISSUE THREAD

**Issue by PaulRosset** [playwright-community/jest-playwright#567]
**Describe the bug**

Hello, 

Thank you for your reactivity for #539 -> [!545](https://github.com/playwright-community/jest-playwright/pull/545)

But, I think there is a little bug that keeps me away from achieving what I want.
  
I think that the bug takes place in the file `src/PlaywrightRunner.js` at line [118](https://github.com/playwright-community/jest-playwright/blob/8eac367dab71078668424e31408c4e1b4ffa5b8d/src/PlaywrightRunner.ts#L118)

Here, u land a new browser server instance only if the base browser (chromium, firefox, webkit) was not already created.

But, In our case, the base browser has already been launched since it's just chromium with a different `executablePath` property.

 So, for example, if I use that config:

```
 browsers: [
        {
          name: 'chromium',
          displayName: 'Edge Chromium',
          launchOptions: {
            headless: false,
            executablePath:
              process.env.EDGE_EXEC_PATH || '/usr/bin/microsoft-edge',
          },
        },
        {
          name: 'chromium',
          displayName: 'Chrome',
          launchOptions: {
            headless: false,
            executablePath:
              process.env.CHROME_EXEC_PATH || '/usr/bin/google-chrome-stable',
          },
        },
]
```

Two browsers instance will be launched but both with the same `executablePath` since the second will be reused based on the first launch since it's still chromium.

We may base that reusability on the `executablePath`  now?

I managed to achieve what I want by removing that line 118 where the `if` condition takes place.

I can land a PR, but maybe that condition is necessary for another use case?

Thanks :)

**Comment by mmarkelov** [comment]
@PaulRosset I believe that removing this condition won't fix issue. https://github.com/playwright-community/jest-playwright/blob/8eac367dab71078668424e31408c4e1b4ffa5b8d/src/PlaywrightRunner.ts#L118

What you can do is to use other `launchType`:
```js
browsers: [
        {
          name: 'chromium',
          displayName: 'Edge Chromium',
          launchType: 'LAUNCH',
          launchOptions: {
            headless: false,
            executablePath:
              process.env.EDGE_EXEC_PATH || '/usr/bin/microsoft-edge',
          },
        },
        {
          name: 'chromium',
          displayName: 'Chrome',
          launchType: 'LAUNCH',
          launchOptions: {
            headless: false,
            executablePath:
              process.env.CHROME_EXEC_PATH || '/usr/bin/google-chrome-stable',
          },
        },
]
```

With this config you will launch browser instead of launching server. And for your case I'll need some time to think about. We just need other kind of specific identification of browser

**Comment by PaulRosset** [comment]
Thank you for your answer, defining the `launchType` to `LAUNCH` has worked for me!
