### ISSUE TITLE
Set high timeout when PWDEBUG env var is set

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#594]
**Is your feature request related to a problem? Please describe.**
I want to more easily debug Playwright errors with jest-playwright.

**Describe the solution you'd like**
Playwright has an Inspector feature https://playwright.dev/docs/inspector/ that let's you `PWDEBUG=1`, which launches browsers in headed mode etc. One can also use `await page.pause();`.

Does this work out of the box with jest-playwright? Can it be documented in the README?

**Describe alternatives you've considered**
None, because I like jest-playwright.

**Comment by mxschmitt** [comment]
Hi, yes it should work! When the Jest timeout is high enough, then you can also skip through the different steps. Will test it later.

**Comment by thernstig** [comment]
@mxschmitt Could `jest-playwright` auto-set the timeout high enough? I suppose another alternative is to document in the README for users to set the timeout to a high timeout if `PWEDBUG` is true.

**Comment by mxschmitt** [comment]
Should be doable 👍

**Comment by mmarkelov** [comment]
@thernstig just made PR to increase jest timeout under hood. It will be available in the next release. But for now you should do it by yourself.

**Comment by thernstig** [comment]
@mmarkelov I had two comments here: https://github.com/playwright-community/jest-playwright/pull/596/files - tips to improve the docs :)
