### ISSUE TITLE
Unable to use jest-playwright with jest 1.9.1

### ISSUE THREAD

**Issue by stuartleeks** [playwright-community/jest-playwright#595]
**Describe the bug**
After updating jest to 1.9.1 (to get the [`page.pause()` method](https://playwright.dev/docs/api/class-page/#pagepause)) I cannot run my jest-playwright tests. 

**To Reproduce**
Running tests after updating jest to 1.9.1:

```
Argument of type 'import("/workspaces/bookings/ui-tests/node_modules/playwright-core/types/types").Page' is not assignable to parameter of type 'import("/workspaces/bookings/ui-tests/node_modules/playwright/types/types").Page'.
      Property 'pause' is missing in type 'import("/workspaces/bookings/ui-tests/node_modules/playwright-core/types/types").Page' but required in type 'import("/workspaces/bookings/ui-tests/node_modules/playwright/types/types").Page'
```

**Expected behavior**
Running with jest 1.9.1 works fine and I am able to call `page.pause()`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Playwright version 1.9.1
 - jest-playwright version 1.4.7

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
module.exports = {
    verbose: true,
    preset: 'jest-playwright-preset',
    transform: {
        '^.+\\.ts$': 'ts-jest',
    },
}
```

**Additional context**
Tests ran fine with jest 1.8.1

**Comment by mxschmitt** [comment]
Hi, you have to upgrade playwright-core too.

`npm install playwright-core@latest`

**Comment by stuartleeks** [comment]
Thanks, I added playwright-core at 1.9.1 but I'm still getting the same error

```json
  "dependencies": {
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.31",
    "jest": "^26.6.3",
    "jest-playwright-preset": "^1.4.7",
    "playwright": "^1.9.1",
    "playwright-core": "^1.9.1",
    "expect-playwright": "0.3.2",
    "ts-jest": "^26.5.1",
    "typescript": "^4.1.5"
  },
```

**Comment by mmarkelov** [comment]
@stuartleeks looks strange. Just tried my tests with new version and it was ok

**Comment by stuartleeks** [comment]
Indeed, I just created a test project and it worked fine there 😄 I will continue trying to troubleshoot in my original project!
