### ISSUE TITLE
Re-work how jestPlaywright.debug() works under the hood (or remove it completely?)

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#608]
**Is your feature request related to a problem? Please describe.**
Playwright supports debugging out of the box. E.g. one can use [`page.pause()`](https://playwright.dev/docs/api/class-page/?_highlight=paus#pagepause) to stop execution in a script (if running in headed/headful mode). In addition, one can set `PWDEBUG=1` which will automatically set Playwright to use [headful mode as well as disable all timeouts](https://playwright.dev/docs/debug#run-in-debug-mode).

`jestPlaywright.debug()` is a current, hacky solution that came with `jest-puppeteer`. It would be good if it is re-worked instead to work better with Playwright's debugging tools/options (and Jest's as well, where applicable).

**Describe the solution you'd like**
I will leave this to your discretion. But setting `PWDEBUG=1` could probably be the way for `jest-playwright` to also set all its debug?

**Describe alternatives you've considered**
No idea.

**Additional context**
Check comments at https://github.com/playwright-community/jest-playwright/pull/596#discussion_r584122431

**Comment by mxschmitt** [comment]
I would vote to remove this functionality and the users should use playwright.pause instead.

**Comment by thernstig** [comment]
You mean `page.pause()`?

**Comment by thernstig** [comment]
Oh, and I agree. That would definitely be a simple solution to fix this.
