### ISSUE TITLE
jest-playwright.config.js in project root not working

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#61]
The documentation states:

> You can specify a jest-playwright.config.js at the **root of the project**

This is not true, as with the below configuration, where one use **Jest projects**, it does not find `jest-playwright.config.js` by default if it is placed in the project's root dir:

```javascript
module.exports = {
  verbose: true,
  projects: [
    {
      displayName: 'UNIT:SERVER',
      testEnvironment: 'node',
      rootDir: 'server/',
    },
    {
      displayName: 'E2E',
      preset: 'jest-playwright-preset',
      rootDir: 'tests/',
      setupFilesAfterEnv: [
        '<rootDir>/jest.setup.js',
      ],
    },
  ],
};
```

This forces me to use `JEST_PLAYWRIGHT_CONFIG`, but it would be nice if this plugin actually looked at the Jest project root when finding the file.

**Comment by mmarkelov** [comment]
@thernstig started work on this issue. It must be ok, if you don't use `jest-playwright` command to run your tests. I'm working on full support for all possible cases

**Comment by thernstig** [comment]
@mmarkelov I verified that this now works fine without setting `JEST_PLAYWRIGHT_CONFIG` when running with `jest` CLI - good job.

**Comment by mmarkelov** [comment]
Should be totally fixed in **next** release
