### ISSUE TITLE
Document globalSetup usage

### ISSUE THREAD

**Issue by adamyonk** [playwright-community/jest-playwright#611]
In the documentation there is reference to setting up authentication in `globalSetup` and then sharing that login across all test runs:

> 1. Run tests (for example, with npm run test).
> 2. Login via UI and retrieve authentication state.
>    - In Jest, this can be executed in globalSetup.
> 3. In each test, load authentication state in beforeEach or beforeAll step.

This seems to suggest a setup like:
```javascript
// jest.config.js
module.exports = {
  globalSetup: '<rootDir>/jest.globalSetup.js',
  preset: 'jest-playwright-preset',
  setupFilesAfterEnv: ['expect-playwright', '<rootDir>/jest.setup.js'],
}
```

But there is nothing playwright-related setup when globalSetup runs:
```javascript
// jest.globalSetup.js
module.exports = async function globalSetup() {
  console.log('setting up', Object.keys(global));
};
```

So does going this route require manually setting up playwright, or is there some way to get access to the instance that jest-playwright-preset creates?

**Comment by adamyonk** [comment]
Yeah, correct me if I'm wrong, but `beforeAll` is run before every test in _that_ test file, but if you want to do something only once for _the whole test suite_ it needs to be in `globalSetup`? I think the once-per-test-suite is what I'm after, so I can login once and not have to do it over and over.

**Comment by adamyonk** [comment]
Perhaps there is some way to serialize the `context.storageState()` into memory _once_ and then have it available to any other browser instances?

**Comment by mmarkelov** [comment]
> Yeah, correct me if I'm wrong, but `beforeAll` is run before every test in _that_ test file, but if you want to do something only once for _the whole test suite_ it needs to be in `globalSetup`? I think the once-per-test-suite is what I'm after, so I can login once and not have to do it over and over.

@adamyonk that's true. But I think you can move it to `setupFilesAfterEnv` block:
```js
// jest.config.js
module.exports = {
    "setupFilesAfterEnv": [
        "expect-playwright",
        "jest-playwright-preset/lib/extends.js",
        "./setup.js"
    ],
    preset: 'jest-playwright-preset',
}

// setup.js
beforeAll(async () => {
    // some login stuff
})
```

**Comment by adamyonk** [comment]
Cool, thanks for the info! 
> `setupFilesAfterEnv`
> A list of paths to modules that run some code to configure or set up the testing framework _before each test file_ in the suite is executed.

I think it would be nice to somehow have that happen once-per-suite and not before each test file, but that will work for now.

**Comment by mmarkelov** [comment]
>I think it would be nice to somehow have that happen once-per-suite and not before each test file, but that will work for now.

@adamyonk yes. But i'm not sure in other ways to handle with it. I can try to make it available in `globalSetup`, but i suppose it will be complicated. Right now starting browser occurs in custom environment and we can’t pass playwright stuff to `globalSetup`.

**Comment by Xezed** [comment]
I would like to see this feature too. 
So... can find some time to dive into package myself and try to implement it. 
Are you interested in it @mmarkelov ?

**Comment by mmarkelov** [comment]
@Xezed I'm going to work on this. I think it can be helpful. But it will quite difficult to rewrite

**Comment by Xezed** [comment]
Just FYI I was looking for authentication solution and stumbled upon this thread.
Thank you for being this fast :)

**Comment by Xezed** [comment]
@mmarkelov how long do you think this will take you to implement? Any estimations?
I've just started to implement the solution for my company and this feature is crucial. 
Sorry for being pushy but I need to give my management some estimations to not feel dorky :smile:

**Comment by mmarkelov** [comment]
@Xezed hello! I just made some investigation on it. And just didn't find any suitable solution. It's very treaky to pass playwright object correctly. I thought about the solution that used in [`jest-puppeteer`](https://github.com/smooth-code/jest-puppeteer/issues/88). But this won't cover all cases and will be able to use only if we will launch browser server. So to be honest that’s all what I've done here

**Comment by Xezed** [comment]
Yeah exactly. I need a feature just like in [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer/issues/88).
This issue will reappear in the future, that's for sure. How would you suggest to do one authentication for all tests otherwise?

I have some time to tinker around with it on my own if you don't mind. Can you provide me with some basic insights?
I'm rus btw so you can text me in Telegram: @Xezed or call there. Thank you @mmarkelov :)

**Comment by Xezed** [comment]
There is some misunderstanding happened. :smile: 
I've plunged into source code and found a way to absolutely satisfy my need. 
Created a pull request please merge it :pray:  :pray:  :pray:
