### ISSUE TITLE
Simple test passes for Firefox and fails for Chromium/Webkit

### ISSUE THREAD

**Issue by dialex** [playwright-community/jest-playwright#614]
**Describe the bug**

I have a simple test that pings the Amazon homepage and another that asserts a selector and a text. They both pass in Firefox. If I run the same tests for Chromium or Webkit the first passes and the seconds fails, without any error log so I have no idea what's wrong.

**To Reproduce**

Run this test for Chrome, Firefox and Safari. [Full source available in my repo](#) (run with `make test` or `jest tests/smoke.spec.ts`).

```js
const AMAZON_HOME = "https://amazon.com/";

describe("Amazon", function () {
  it("should be online", async () => {
    await page.goto(AMAZON_HOME);
    expect(page).not.toBeNull();
  });

  it("should render the UI", async () => {
    await page.goto(AMAZON_HOME);
    expect(await page.title()).toContain("Amazon");
    await expect(page).toHaveSelector("#twotabsearchtextbox");
    await expect(page).toHaveText("Departments");
    await expect(page).toHaveText("Cart");
  });
});
```

**Expected behavior**

The same test passes in all browsers.

**Screenshots**

![Screenshot 2021-03-05 at 13 20 45](https://user-images.githubusercontent.com/2140450/110121098-dc175000-7db5-11eb-90a3-bd2a7ca7d994.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2
 - Playwright version 1.9.0
 - jest-playwright version 1.4.7
 - jest version 26.6.3

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
module.exports = {
  preset: "jest-playwright-preset",
  testEnvironmentOptions: {
    "jest-playwright": {
      // browsers: ["chromium", "firefox", "webkit"],
      browsers: ["firefox"],
      launchOptions: {
        // headless: true,
      },
    },
  },
};

```

**Additional context**
N/A

**Comment by mmarkelov** [comment]
@dialex seems like that were page errors for **chromium** and **webkit** browsers, and by default it will fail your tests. So it should be fine with this config:
```js
module.exports = {
 preset: "jest-playwright-preset",
 testEnvironmentOptions: {
   "jest-playwright": {
     browsers: ["chromium", "firefox", "webkit"],
     exitOnPageError: false,
     launchOptions: {
       // headless: true,
     },
   },
 },
};
```

**Comment by dialex** [comment]
ok... I'm a bit concern about **ignoring** the page errors. Why would there be page errors only for Chrome/Safari?

I followed your suggestion now Chromium passes, and Webkit fails most of the time with _timeout_. Only once it passed:

<img width="668" alt="Screenshot 2021-03-05 at 17 28 21" src="https://user-images.githubusercontent.com/2140450/110151408-5b1d8000-7dd8-11eb-8546-0ab85bd5fb61.png">

No idea why Webkit takes almost _3x more time_ than the other browsers. Also, if I run it with `headless: false` then Webkit _always passes_. I was not expecting this amount of **flakiness** for such a simple test.

**Comment by mmarkelov** [comment]
@dialex that's fine to skip page errors. For example for **chrome** they are about missed fonts:
```
[Error: DOMException: Could not resolve 'light 1em Amazon Ember' as a font.]
[Error: DOMException: Could not resolve 'medium 1em Amazon Ember' as a font.]
[Error: DOMException: Could not resolve 'italic light 1em Amazon Ember' as a font.]
[Error: DOMException: Could not resolve 'italic medium 1em Amazon Ember' as a font.]
```

For **webkit** you got this:
```
[Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.]
```

And this is error which you can see when you open developer console in Safari browser.

I don't have any ideas why Webkit takes so much time. And not sure that it is related to `jest-playwright` somehow.  
You can try to run your test directly https://playwright.dev/docs/test-runners?_highlight=test

**Comment by dialex** [comment]
Thanks a lot for your patience and explanation 🙇‍♂️
