### ISSUE TITLE
incorrect usage of devdependencies

### ISSUE THREAD

**Issue by rseeberg** [playwright-community/jest-playwright#615]
**Describe the bug**
The `playwright` and `playwright-chromium` dependencies listed in "DevDependencies" are actually being used in the runtime.
When using a strict packagemanager these will not be available.

**To Reproduce**
Try to use with yarn2 pnp enabled, and notice nothing is working

**Desktop (please complete the following information):**
 - OS: windows10
 - Playwright version latest
 - jest-playwright version latest

**Additional context**
The problem arises from how imports are done in the utils.ts where it uses the `IMPORT_KIND_PLAYWRIGHT` and a browser string, to generate a require call. this require call is targeting "playwright-chromium" for instance, which is not actually available due to being a devDependency. Moving it into dependencies solves this issue

**Comment by mxschmitt** [comment]
Hi, jest-playwright is designed that the user has to install either playwright or e.g. playwright-chromium to use jest-playwright. This allows setups, that a user e.g. only wants chromium or some whole playwright. Does this answer your question?
