### ISSUE TITLE
Issue with saving videos when we use jestPlaywright.resetContext()

### ISSUE THREAD

**Issue by ychaudhari** [playwright-community/jest-playwright#626]
**Describe the bug**
resetContext() saves incorrect number of video files

**To Reproduce**
Run following test for two browsers (e.g. firefox and chromium) with 
```javascript
describe('Testing', () => {
  beforeEach(async () => {
    await jestPlaywright.resetContext();
  });
  it('test1', async () => {
    await page.goto('http://www.google.com');
  });
  it('test2', async () => {
    await page.goto('http://www.bing.com');
  });
});
```

**Expected behavior**
It should save only 4 video files
(or 8 if video starts saving on global context/page before resetContext() is executed, and saves an empty file because of context closing before running the test)

**Actual behavior**
It saves 6 video files

**Screenshots**
![image](https://user-images.githubusercontent.com/12400832/110516983-21999b80-816f-11eb-9b90-0bfe2a334087.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Playwright version 1.9.1
 - jest-playwright version 1.5.1

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

`jest-playwright.config.js`

 ```javascript
module.exports = {
  browsers: ['chromium', 'firefox'],
  connectOptions: {},
  contextOptions: {
    recordVideo: {
      dir: './output',
      size: {
        width: 800,
        height: 600,
      },
    },
  },
  launchOptions: {
    headless: true,
  },
};
```

`jest.config.ts`

```typescript
import type { Config } from '@jest/types';

// https://jestjs.io/docs/en/configuration
export default async (): Promise<Config.InitialOptions> => {
  return {
    verbose: true,
    setupFilesAfterEnv: ['./jest.setup.ts', 'expect-playwright'],
    preset: 'jest-playwright-preset',
    testMatch: ['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)'],
    testPathIgnorePatterns: ['/node_modules/', '/helpers/'],
    transform: {
      '^.+\\.ts?$': 'ts-jest',
    },
    reporters: [
      'default',
      // https://www.npmjs.com/package/jest-junit
      [
        'jest-junit',
        {
          outputDirectory: './output/',
        },
      ],
    ],
    testEnvironment: './CustomEnvironment.js',
    testTimeout: 60000,
  };
};
```

**Comment by mmarkelov** [comment]
@ychaudhari that makes sense. Playwright save videos on `context` close.
https://playwright.dev/docs/videos?_highlight=recordvideo

And for you cases there are 6 times when `jest-playwright` close context. (4 times in your tests in `resetContext`, 2 times - in `PlaywrightEnv` `teardown`).

IDK how can we handle this cases. Cause we need to close **browser** and when we do it - `playwright` create video. As workaround you can pass properties to your `resetContext`:

```js
beforeEach(async () => {
        await jestPlaywright.resetContext({ recordVideo: { dir: 'videos/' } });
});
```

With this config you can be sure that valid videos will be in `videos` directory

**Comment by ychaudhari** [comment]
Ah, that makes sense (I didn't think about `PlaywrightEnv teardown` first)

Thanks for the tip on saving valid videos @mmarkelov !
