### ISSUE TITLE
Ability to use jestPlaywrightConfig with jestPlaywrightSkip

### ISSUE THREAD

**Issue by ychaudhari** [playwright-community/jest-playwright#627]
**Is your feature request related to a problem? Please describe.**
I cannot use jestPlaywrightConfig with jestPlaywrightSkip
Context:
I have a set of visual regression tests in the entire test suite. The entire test suite runs for multiple browsers, but I need to run visual Regression tests for specific browser only (because the screenshot comparison fails when the test runs against a different browser). 
Also, I need to run visual regression test in non-headless mode whereas entire suite runs in headless mode.
Hence, I have two requirements only for these visual regression tests:
1. Run them in non-Headless mode (using jestPlaywrightConfig)
2. Skip them for other browsers (using jestPlaywrightSkip)

**Describe the solution you'd like**
I need to be able to use jestPlaywrightConfig with jestPlaywrightSkip 
[maybe something like it.jestPlaywrightParameters(<where-I-can-use-config + skip + debug-parameters>)]

**Describe alternatives you've considered**
I have considered alternative of having separate `npm` script for these visual regression test and setting config path `JEST_PLAYWRIGHT_CONFIG=jest-playwright.alternate.config.js`

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

It provides various. ways for test.skip() test.only() test.fixme() with custom conditions: https://playwright.dev/docs/test-annotations#skip-a-test
