### ISSUE TITLE
Typescript support for CustomEnvironment

### ISSUE THREAD

**Issue by ychaudhari** [playwright-community/jest-playwright#634]
**Is your feature request related to a problem? Please describe.**
It would be great if you could provide support/example of typescript for CustomEnvironment

**Describe alternatives you've considered**
use CustomEnvironment.js without benefits of typescript

**Comment by mmarkelov** [comment]
@ychaudhari I think that it is related to jest.It will be available in next release

https://github.com/kulshekhar/ts-jest/issues/1445
https://github.com/facebook/jest/pull/8751

**Comment by mmarkelov** [comment]
i suppose that we can close it, **jest@27** was released and you can try it with **jest-playwright-preset@next**
