### ISSUE TITLE
Docs: Remove jestPlaywrightDebug ?

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#636]
https://github.com/playwright-community/jest-playwright#jestplaywrightdebug mentions the use of `jestPlaywrightDebug`. But with the support for `PWDEBUG=1 jest` is `jestPlaywrightDebug` needed anymore? If not it should be removed from the docs and code.

Sorry for not using the template but it feels way too elaborate for something like this that exists in the README.md 😝

**Comment by mmarkelov** [comment]
@thernstig this is helper function to simplify [debugging process](https://github.com/playwright-community/jest-playwright/issues/216). But this is not related to `jestPlaywright.debug()` that we removed.

**Comment by thernstig** [comment]
I was aware, but I just did not see the reason for `test.jestPlaywrightDebug`. One can easily do `if (process.env.PWDEBUG)` in `jest-playwright.config.js`. I thought it might simplify some logic for you and you could just describe how to use that env var.
