### ISSUE TITLE
Unable to get the "Usage with custom globalSetup and globalTeardown" example working

### ISSUE THREAD

**Issue by jignesh-dalal** [playwright-community/jest-playwright#645]
Can someone help me with a working example for the section "Usage with custom globalSetup and globalTeardown"?

I tried the following:
- Error 1: Cannot use import statement outside a module - Changed `import { globalSetup as playwrightGlobalSetup } from "jest-playwright-preset";` to `const playwrightGlobalSetup = require("jest-playwright-preset").globalSetup;`  
- Error 2: chromium is not defined - No idea how to resolve this :(

OS: Windows 10
Node: 14.16

**Comment by jignesh-dalal** [comment]
Finally got it working by replacing `import { globalSetup as playwrightGlobalSetup } from "jest-playwright-preset";` with the following:

`const { chromium } = require("playwright");
const playwrightGlobalSetup = require("jest-playwright-preset").globalSetup;`

Hope it helps!

**Comment by danial-k** [comment]
Alternatively, the `global-setup.js` could be changed to:
```js
const { globalSetup } = require('jest-playwright-preset');
const { chromium } = require('playwright');

module.exports = async (globalConfig) => {
  await globalSetup(globalConfig);

  const browserServer = await chromium.launchServer();
  const wsEndpoint = browserServer.wsEndpoint();
  const browser = await chromium.connect({ wsEndpoint: wsEndpoint });
  const page = await browser.newPage();

  // your login function
  await doLogin(page);

  // store authentication data
  const storage = await page.context().storageState();
  process.env.STORAGE = JSON.stringify(storage);
};
```
@mmarkelov , is it worth updating the docs as this might catch others out that aren't using ESM?
