### ISSUE TITLE
jest-playwright-preset 1.5.1 not working with playwright 1.10.0 and jest 24.9.0

### ISSUE THREAD

**Issue by cscheffauer** [playwright-community/jest-playwright#647]
**Describe the bug**
When using the following versions in a project (package.json):
```json
  ...
  "jest": "24.9.0",
  "jest-playwright-preset": "1.5.1",
  "playwright": "1.10.0",
  ...
```
the npm install failed with `cb() never called!`  

**To Reproduce**
Modify the package.json as above and install.

**Expected behavior**
Should not happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/29776408/112469411-bf918680-8d69-11eb-85b3-34d94a42b6e9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Playwright version: 1.10.0
 - jest-playwright version: 1.5.1

**Comment by mxschmitt** [comment]
I tried to reproduce it with Playwright 1.10 and the latest jest-playwright version but was not able too.

Ref: https://github.com/playwright-community/playwright-jest-examples/pull/23

did it work before? Jest 24.9.0 seems super old. Over 2 years. Thats probably the reason, try Jest 26 (latest) instead.

**Comment by mxschmitt** [comment]
Closed since Jest > 26 is required.

**Comment by cscheffauer** [comment]
@mxschmitt yes - the new version of Jest fixed the issue :) could this probably be added to the documentation?  
maybe here?  
https://github.com/playwright-community/jest-playwright#requirements  

Thank u!

**Comment by mxschmitt** [comment]
@mmarkelov what do you think about adding jest > 26 to the peerDependencies?

**Comment by mmarkelov** [comment]
> @mmarkelov what do you think about adding jest > 26 to the peerDependencies?

that makes sense
