### ISSUE TITLE
launchOptions value is not reflect when the test is running

### ISSUE THREAD

**Issue by tannguyenphuc** [playwright-community/jest-playwright#650]
**Describe the bug**
I am using the jest-playwright.config.js to add some options when my tests are running. In the basic playwright run it works but when I use jest-playwright and set the configurations exactly like before it does not work. I use **launchOptions** in the config file

**To Reproduce**
Add the below options in the jest-playwright.config.js file
![jest-playwright-issue](https://user-images.githubusercontent.com/73222007/112787075-e90c2400-9081-11eb-95f9-1dd7c6432d98.gif)

**Expected behavior**
Tests should be run with no headless and use the executable path provided in the config file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS or Windows]
 - Playwright version [e.g. 1.1.1]
 - jest-playwright version [e.g. 1.0.0]

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
module.exports = {
  browsers: ["chromium"],
  launchOptions: {
    headless: false,
    executablePath: "C:\\Users\\tan.nguyenphuc\\AppData\\Local\\ms-playwright\\chromium-854489\\chrome-win\\chrome.exe",
  },
};
```

**Additional context**

**Comment by mmarkelov** [comment]
Just tried on my local mac and it's OK. @mxschmitt can it be related to windows machine maybe?

**Comment by mxschmitt** [comment]
@tannguyenphuc could you show us your test files? Feel free to remove there any company / private related code.

**Comment by tannguyenphuc** [comment]
[files.zip](https://github.com/playwright-community/jest-playwright/files/6233514/files.zip)
Hi @mxschmitt  Please refer to my files in the attachment.

**Comment by mxschmitt** [comment]
The reason is that you are launching a new Chromium instance and Context manually in your `beforeAll`.

Jest-playwright does automatically launch a browser and context for you which is available as a global variable. So if you modify it to the following your file, then it works as expected:

```js
/// <reference types="jest-playwright-preset" />
import { HomePage } from "../page-object/home.page";
import { AccountPage } from "../page-object/account.page";

let homePage: HomePage;
let accountPage: AccountPage;

beforeAll(async () => {
  homePage = new HomePage(page);
  await homePage.navigateToHomePage();
  await homePage.doLogin("user@email.com", "supersecure1");
  accountPage = await homePage.clickAccountIcon(page);
});

afterAll(async () => {
  await browser.close();
});

it("Verify the Home page Title", async () => {
  expect(await page.title()).toBe("danube-store");
});
```

The first line gives you also typing support.
