### ISSUE TITLE
[QUESTION] How to run jestPlayWightDebug on browser from executable path?

### ISSUE THREAD

**Issue by mostor-v** [playwright-community/jest-playwright#667]
**Is your feature request related to a problem? Please describe.**
I'm not able to download any exe which are out of my local network, so i can't download chromium
I've configured playwright to run in from executable path, but i can't run in debug mode (`it.jestPLaywrightDebug`)
Error: Failed to launch chromium because  executable doesn't exists [ ...path to folder where downloaded by playwright chromium should exist]

**Comment by mmarkelov** [comment]
@mostor-v it's quite difficult to understand. This works for me:
```js
it.jestPlaywrightDebug({
    launchOptions: {
      executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
    }}, 'test', async ({page}) => {
    await page.goto("https://google.com");
    expect(await page.title()).toBe('Google')
  })
```

**Comment by mostor-v** [comment]
> @mostor-v it's quite difficult to understand. This works for me:
> 
> ```js
> it.jestPlaywrightDebug({
>     launchOptions: {
>       executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
>     }}, 'test', async ({page}) => {
>     await page.goto("https://google.com");
>     expect(await page.title()).toBe('Google')
>   })
> ```

Your chrome downloaded via playwright installation process?

**Comment by mmarkelov** [comment]
@mostor-v nope. This is my installed Google Chrome

**Comment by mostor-v** [comment]
@mmarkelov After I specify PWDEBUG=1 executable path is changed to directory where should be installed chrome via playwright installation process.
  launchOptions: {
      executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
    }}
This part of code doesn't override  that path

**Comment by mmarkelov** [comment]
> This part of code doesn't override that path

I think this because that it try to run `chromium` instance. You could try to set  `executablePath` also in `jest-playwright.config`

```js
// jest-playwright.config.js
module.exports = {
	launchOptions: {
		executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
	}
};
```

**Comment by mostor-v** [comment]
@mmarkelov I have this options in my config file. In Normal mode Playwright start browser from this location but in Debug mode this path overrided

**Comment by mmarkelov** [comment]
@mostor-v I'm not sure that `jest-playwright` made any changes with `Debug Mode`. Can you run test script with playwright. It can be something that related to `playwright`, cause as i can noticed **Playwright Inspector** is using `chromium`
<img width="151" alt="Снимок экрана 2021-04-09 в 19 52 49" src="https://user-images.githubusercontent.com/22371328/114214603-2c616f00-996d-11eb-86ed-6ab684cf288f.png">
`

**Comment by mostor-v** [comment]
@mmarkelov Looks like this is playwright bug 
https://github.com/microsoft/playwright/issues/6158
