### ISSUE TITLE
test.concurrent feature not working

### ISSUE THREAD

**Issue by lala7573** [playwright-community/jest-playwright#689]
**Describe the bug**
Hi, there. 
I'm trying to use jest-playwright instead of jest-puppeteer and struggled with testing in parallel. 
If you guys tell me anything that might help, I'd really appreciate it. 

There've been parallel capturing test sets like below. But when I changed jest config with jest-playwright, then the tests run serially, not in parallel. The test set captures the screenshot one by one.
```
test.concurrent.each(
  pages.map(({ name, url, waitForSelector }) => [name, url, waitForSelector]),
)('capture %s on %s', async (name, url, waitForSelector) => {
  console.log('start to capture: ', name);

  const page = await context.newPage()
  await page.goto(url, { waitUntil: 'networkidle' });
  await page.waitForSelector(waitForSelector);
  await sleep(3, 'second')
  const app = await page.$('#app');
  await app?.screenshot({ path: name });
});

```
I checked the differences between the playwright and puppeteer jest option using '--showConfig' option on jest, and then I found the runner is different. jest-puppeteer uses default 'jest-runner', but jest-playwright uses it's own runner, 'jest-playwright/runner.js'. But I'm not sure this makes some differences.

**Desktop (please complete the following information):**
 - OS: macOS
 - Playwright version [e.g. 1.1.1]
```
// package.json
// ...
"expect-playwright": "^0.3.4",
"jest": "^26.6.3",
"jest-playwright": "^0.0.1",
"jest-playwright-preset": "^1.5.2",
"playwright": "^1.10.0",
```
**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

```
module.exports = {
  preset: 'jest-playwright-preset',
  globalSetup: "jest-playwright-preset/setup.js",
  globalTeardown: "jest-playwright-preset/teardown.js",
  setupFilesAfterEnv: ["expect-playwright"],
};
```

**Additional context**

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

It provides horizontal and vertical parallelisation. Also on the test level: https://playwright.dev/docs/test-parallel

**Comment by nagisaando** [comment]
Thank you, this approach saved my day!!
