### ISSUE TITLE
Test case working fine in firefox browser but in chromium it fails without any error.

### ISSUE THREAD

**Issue by Ppkd2021** [playwright-community/jest-playwright#691]
**Describe the bug**
All the steps are executed fine in chromium-browser  but it publishes the test result as failed both in CI and locally. When the same test case is executed using firefox browser then it seems to be working fine and publish the test result as pass.

**To Reproduce**

**Expected behavior**
90% of our users use chrome so it will be great if you could tell a resolution for this issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/59794856/117322481-acff8680-aeab-11eb-92cc-a39775546517.png)
e, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Playwright version [1.9.1]
 - jest-playwright version [1.4.4]

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
<module.exports = {
	verbose: true,
	globals: {
		'ts-jest': {
			tsConfig: './tsconfig.test.json'
		}
	},
	preset: 'jest-playwright-preset',
	transform: {
		'^.+\\.ts$': 'ts-jest'
	},
	testMatch: ['**/playwright/e2e/user-onboarding-journey/FacebookAcessToken.test.ts'],
	reporters: [
		'default',
		[
			'jest-junit',
			{
				outputDirectory: './test-reports',
				outputName: 'results.xml',
				usePathForSuiteName: true,
				classNameTemplate: '{classname}-{title}'
			}
		]
	],
	testRunner: 'jest-circus/runner',
	//testEnvironment: './customEnvironment.js',
	testTimeout: 200000,
	setupFilesAfterEnv: ['expect-playwright'],
	verbose: true
	
};
>
```

**Additional context**

**Comment by mmarkelov** [comment]
@Ppkd2021  IDK what can be wrong. Maybe there is some kind of specific **chrome** error. So could you please try to set **exitOnPageError** in your config to **false**:
```js
// jest-playwright.config.js
module.exports = {
  ...
  exitOnPageError: false
}
```

**Comment by thernstig** [comment]
This seems more like an error that should be reported on `playwright` rather than here. But I'd be surprised if this is not an user error, considering so many are using Chrome with Playwright to test.

**Comment by mxschmitt** [comment]
Closed since stale.
