### ISSUE TITLE
ECMAScript modules support (and docs)

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#718]
**Is your feature request related to a problem? Please describe.**

Most of the examples in the README.md is using CommonsJS `require/export`. Some docs use ECMAScript modules `import/export`

Considering Node.js 10 has reached EOL, and that Jest 27 has released, the whole community is rallying around ESM. I think it would make sense to update all documents to be in ESM rather than CJS.

**Edit**: It seems `jest-playwright` does not support e.g. `jest-playwright.config.js` to be written in ESM. So the request is to support ESM. See below.

**Comment by thernstig** [comment]
I realize we cannot use ESM with this package by default without "hacks". Which is a shame as ESM is becoming so prevalent right now.

Could the repo be updated to support this? Here is an example when trying to write `jest-playwright.config.js` in ESM:

```sh
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/userA/code/projectA/tests/e2e/jest-playwright.config.js
require() of ES modules is not supported.
require() of /home/userA/code/projectA/tests/e2e/jest-playwright.config.js from /home/userA/code/projectA/node_modules/jest-playwright-preset/lib/utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename jest-playwright.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/userA/code/projectA/package.json.
```

If the repo was updated to use `import()` instead of `require()` then ESM should work. See https://nodejs.org/api/esm.html#esm_require

**Comment by mmarkelov** [comment]
@thernstig thanks for your issue. IDK if we should keep compatibility with `commonJS`, cause i suppose that it will be quite complicated to keep this for both `esm` and `commonJS`

**Comment by thernstig** [comment]
@mmarkelov from my perspective I would be fine with you just supporting ESM. But that is a decision for you and @mxschmitt to take.

**Comment by thernstig** [comment]
@mmarkelov did you reach a consensus about this? Jest-Playwright is one of the last pieces of the puzzle for us to not have to use CommonJS in our entire code base.

**Comment by mmarkelov** [comment]
@thernstig sorry for late response. I just tried to keep it compatibility for  `esm` and `commonJS` but it was difficult for me. I suppose that I can change it for the **next** release. Unfortunately don’t have much free time right now, so cannot tell you when it will be ready. Sorry, for that :(

**Comment by thernstig** [comment]
I understand, you should not need to be sorry about it. I wish I had the time for an open source project, but I don't 😞 I try to help here and there instead.

If both you and @mxschmitt has limited time, would it be time for you to advertise that you need more core maintainers? Maybe there are people willing to help.

**Comment by mmarkelov** [comment]
@thernstig i just put `help wanted` label for this task to let developers that they can start their contribution from this issue. But i suppose that it won't help) I just try to find out some time on this task in a couple weeks

**Comment by mmarkelov** [comment]
@thernstig i just put `help wanted` label for this task to let developers that they can start their contribution from this issue. But i suppose that it won't help) I just try to find out some time on this task in a couple weeks

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

The official test-runner provides esm support out of the box!

**Comment by thernstig** [comment]
@mxschmitt then I think that the README.md should be updated:

> It's more flexible, lightweight, optimized for Playwright, and has TypeScript support out of the box. This doesn't mean, that we stop with maintaining this package.
