### ISSUE TITLE
jest-playwright does not work with jest 27.0

### ISSUE THREAD

**Issue by daliusd** [playwright-community/jest-playwright#720]
**Describe the bug**
jest-playwright does not work with jest 27.0

**To Reproduce**
Here I have repository with jest used without and with jest-playwright. This PR is attempt to upgrade to newest jest https://github.com/daliusd/apskaita/pull/353

**Expected behavior**
It should work

**Screenshots**
![image](https://user-images.githubusercontent.com/1944737/119999413-67316c00-bfda-11eb-8a62-d1de54b4fd20.png)

**Comment by mmarkelov** [comment]
@daliusd i think that this is related to #665 and it should be ok in **next** release. I just need some more time to check some cases and will publish **1.6.0** soon.

**Comment by daliusd** [comment]
Good to hear that. I will wait when for a version with a fix and close then this issue.

**Comment by daliusd** [comment]
Problem is solved. The only problem that I need to add `jest-environment-node` as dependency.
