### ISSUE TITLE
How can I run tests on all browsers in parallel using jest-playwright

### ISSUE THREAD

**Issue by snehalk20** [playwright-community/jest-playwright#721]
I am trying to use jest-playwright.
I have all 3 browsers in my jest config file.
In a single test file I have 3 tests.
When I run the tests using "jest" command, I see that the tests are running sequentially on each browser one after another.
However, I would like to run the tests on all browsers in parallel. i.e. all 3 browsers should be launched at a time.
How can I achieve this?

**Comment by mikementor** [comment]
Looks like  https://github.com/playwright-community/jest-playwright/issues/257.

  thank you! Unfortunately you can't run same tests for multiple browsers in parallel. I just made some research on it, but the solution is very unstable. So for a now there is no plans to support this feature. Maybe I'll put this solution in separate package. But for now I just don't have enough time to do it.

_Originally posted by @mmarkelov in https://github.com/playwright-community/jest-playwright/issues/257#issuecomment-667841129_cc @mmarkelov

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

It provides horizontal and vertical parallelisation. Also on the test level: https://playwright.dev/docs/test-parallel
