### ISSUE TITLE
QUESTION: Will jest-playwright be supported, once playwright-test 1.0 is released?

### ISSUE THREAD

**Issue by radekBednarik** [playwright-community/jest-playwright#730]
Hello, I am currently thinking about, what test runner would be best to use for long-term project for e2e test automation of the web app. 
The viable options, as I see them, are for me either jest + jest-playwright or mocha + chai.
As of now, I am inclined to use jest + jest-playwright, however, I have noticed, that microsoft is working on its own playwright test runner https://github.com/microsoft/playwright-test .
So my question is - will jest-playwright be supported even after the playwright-test 1.0 release?
Thank you.

Best

RB

**Comment by mmarkelov** [comment]
@radekBednarik, thank you for your question. I don't have any plans to stop support `jest-playwright`, but you also keep in mind that this is an open source project and sometimes i don't have much time to give feedback, implement new features or fix bugs.

**Comment by radekBednarik** [comment]
@mmarkelov hello, thank you for the answer
