### ISSUE TITLE
[1.6.0]custom handleTestEvent cannot be processed

### ISSUE THREAD

**Issue by xuanzhaopeng** [playwright-community/jest-playwright#732]
**Describe the bug**
https://github.com/playwright-community/jest-playwright/blob/master/src/PlaywrightEnvironment.ts#L350 once update from 1.5.6 to 1.6.0

**To Reproduce**

```js
class MyPlaywrightEnvironment extends PlaywrightEnvironment {
	constructor(config, context) {
		super(config)
		console.log('My Playwright Environment!!!!!!')
	}

	async setup() {
		return super.setup()
	}

	async teardown() {
		return super.teardown()
	}

	async handleTestEvent(event, state) {
		console.log('111111  !!!!!!!!!! Handle!!!!!!!  !!!!!!')
		await super.handleTestEvent(event);
		console.log('222222  !!!!!!!!!! Handle!!!!!!!  !!!!!!')
        }
}
```

**Expected behavior**
The handleTestEvent function should be called ,  however not.

**Comment by mmarkelov** [comment]
@xuanzhaopeng can you provide some more information? I tried to reproduce, but it's ok for me
<img width="1083" alt="Снимок экрана 2021-06-03 в 11 06 24" src="https://user-images.githubusercontent.com/22371328/120610343-be609200-c45b-11eb-91c8-8d9761505492.png">

**Comment by xuanzhaopeng** [comment]
Hey @mmarkelov ,  may I ask which version of Jest you are using?  

I still can reproduce,   here is jest.config.js
```
module.exports = {
	verbose: true,
	preset: 'jest-playwright-preset',
	testTimeout: Number(process.env.TEST_CASE_TIMEOUT) || 360000,
	testEnvironment: './lib/settings/example-playwright-environment.js',
	testMatch: testMatch,
	setupFilesAfterEnv: ['./lib/settings/jest.setup.ts', 'jest-expect-message'],
	transform: {
		'^.+\\.ts$': 'ts-jest',
	},
}

```

**Comment by xuanzhaopeng** [comment]
I changed to 27.0, then it works, so seems there is issue for compatible with jest 26

<img width="1226" alt="Screenshot 2021-06-03 at 12 31 19" src="https://user-images.githubusercontent.com/5563244/120631002-ab53bf00-c467-11eb-9bc7-bd598bbd0131.png">

**Comment by mmarkelov** [comment]
@xuanzhaopeng yes this is true. We bumped **jest** to **27**, and I removed **testRunner** from **jest** configuration, cause for new version **jest-circus** is default test runner. And I suppose because of it you don't have access to ** handleTestEvent**. So if you need it in **26** you need to change **testRunner** in your **jest.config**
```js
// jest.config.js
module.exports = {
  preset: 'jest-playwright-preset',
  testRunner: 'jest-circus/runner'
}
```

**Comment by xuanzhaopeng** [comment]
Cool thanks @mmarkelov ,  I will switch to use 27.0 then.
