### ISSUE TITLE
Tracing as option

### ISSUE THREAD

**Issue by creage** [playwright-community/jest-playwright#746]
**Is your feature request related to a problem? Please describe.**
Playwright v1.12.0 introduces  new [Tracing](https://playwright.dev/docs/next/trace-viewer/) which adds great value to test run analysis. 

**Describe the solution you'd like**
Would be nice if we can start tracing by option in the `configSeparateEnv()` method, and by a separate parameter in [Options](https://github.com/playwright-community/jest-playwright#options). Something like `tracing: { enabled: true, path: 'path_to_store_trace_to' }`

**Describe alternatives you've considered**
We can use custom jest environment with `setup()`, and `handleTestEvent()` where we can start and stop tracing manually.

**Comment by mmarkelov** [comment]
@creage i just checked it. But idk why do we need new option for tracing. You can just use **context**:
```js
// your test
beforeAll(async () => {
  await context.tracing.start({ screenshots: true, snapshots: true });
});

it("should render the UI", async () => {
  await page.goto(PAGE);
  await context.tracing.stop({ path: 'trace.zip' });
});
```

**Comment by creage** [comment]
Well, this is option too, I agree. But having about a thousand of test files, such approach requires me to update all of them.

DRY, you know.

And, I don't want my test definition to contain any of environment logic, like logging, tracing, screenshotting and what not. Such stuff should be handled separately, I believe.

**Comment by mmarkelov** [comment]
Sorry for so late response. Thinking about this feature i don't know how should we stop `tracing`. Should we do it on **afterAll**?

**Comment by creage** [comment]
@mmarkelov since we already have our own jest environment extension, can we use `setup` and `teardown` methods for that? And, `handleTestEvent` maybe?

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

It supports Tracing out of the box and contains a lot of testing goodies like web-first assertions, parallelisation etc.
