### ISSUE TITLE
[BUG] video isn't recorded when set "recordVideo" option in "contextOptions" of jest-playwright.config.js 

### ISSUE THREAD

**Issue by Yurii397** [playwright-community/jest-playwright#752]
**Context:**
- Playwright Version: [1.12.0]
- "jest-playwright-preset" version: [1.6.0],
- Operating System: [Mac]
- Node.js version: [v16.2.0]
- Browser: [e.g. All]

**Code Snippet**
This is my `jest-playwright.config.js` config file

```
module.exports = {
    preset: 'jest-playwright-preset',
    testMatch: [
        '<rootDir>/ui-tests/**/*.spec.ts'
    ],
    browsers: [process.env.BROWSER || 'chromium'],
    devices: ['iPad Pro 11'],
    launchOptions: {
        headless: process.env.BROWSER_MODE || true,
        devtools: process.env.BROWSER_DEVTOOL || false,
        slowMo:50
    },
    exitOnPageError: true,
    contextOptions: {
        recordVideo: {
            dir: './videos',
            size: { width: 640, height: 480 },
        }
    },
    setupFilesAfterEnv: ['<rootDir>/ui-tests/utils/setup.ts']
}
```

The folder with the video doesn't appear. When I do the same through the jest hooks using  browser.newContext() it works fine. 

```javascript
 browser.newContext({
        recordVideo: {
            dir: "./video",
            size: {width: iPadPro.viewport.width, height: iPadPro.viewport.height}
        // },
    });
```

What is the difference? Did I miss something? Looks did the same as described here - https://playwright.tech/blog/record-your-browser-tests-with-playwright

**Comment by mxschmitt** [comment]
using `launchType: "LAUNCH"` should fix it.

**Comment by AfroJoe759** [comment]
@mxschmitt In my case, using do ``launchType: "LAUNCH"`` does generate the video files, but with the caveat of breaking recordHar functionality. Is there a known way for me to do both in the jest-playwright.config.js?
