### ISSUE TITLE
Support for playwright version 1.13.0 - Getting error on upgrading to playwright 1.13.0

### ISSUE THREAD

**Issue by cheytan86** [playwright-community/jest-playwright#770]
On upgrading playwright to latest version, the existing scripts shows type error for global  page declaration. Refer teh attached screenshot.
Throwing the following error:
Argument of type 'import("/Users/chetanmalhotra/code/TestAutomation/ts-playwright/node_modules/jest-playwright-preset/node_modules/playwright-core/types/types").Page' is not assignable to parameter of type 'import("/Users/chetanmalhotra/code/TestAutomation/ts-playwright/node_modules/playwright/types/types").Page'.

**To Reproduce**
Install the latest version of playwright 1.13.0 (npm i playwright) on your existing project

**Expected behavior**
The scripts should work fine on upgrading to latest version of playwright. But now it's showing type error for global page fixture.

 - OS: [e.g. macOS or Windows] macOS
 - Playwright version [e.g. 1.1.1] 1.13.0
<img width="1212" alt="Screenshot 2021-07-27 at 7 03 32 PM" src="https://user-images.githubusercontent.com/33166252/127144111-472ced8b-0814-48ab-9420-4f43ec256226.png">

 - jest-playwright version [e.g. 1.0.0] - 1.7.0

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
    verbose: true,
    roots: ["<rootDir>/src"],
    preset: 'jest-playwright-preset',
    testRunner: "jasmine2",
    testTimeout: 200000,
    reporters:["default",["jest-junit",{"outputDirectory": "./test-results"}]],
    transform: {
        '^.+\\.ts$': 'ts-jest'
    },
    setupFilesAfterEnv: ["jest-allure/dist/setup"],
    testMatch: [
        "<rootDir>/src/test/**.ts"
    ],
}
```

**Additional context**

**Comment by mxschmitt** [comment]
Did you also upgrade playwright-core in your package.json?

**Comment by cheytan86** [comment]
playwright-core was not there are a dependency in package.json , it was referring jest-playwright-preset. I have added it as dependency and it seems to work fine now.
