### ISSUE TITLE
[Question] How to use PlaywrightEnvironment with Typescript?

### ISSUE THREAD

**Issue by mostor-v** [playwright-community/jest-playwright#771]
Hi, I see PlaywrightEnvironment.ts file in repository  (src->PlaywrightEnvironment.ts), but while I make yarn install I don't see that file and can't extend it using Typescript.
All versions are latest.
jest = 27.0.6
ts-jest = 27.0.4
jest-playwright = 1.7.0
playwright = 1.13.0

**Comment by mmarkelov** [comment]
@mostor-v `PlaywrightEnvironment.ts` will be compiled to js file. But you should be able to use typescript with your custom environment. It will be pretty close to regular js file https://github.com/playwright-community/jest-playwright#usage-with-custom-testenvironment

**Comment by mostor-v** [comment]
@mmarkelov I can't use types from PlaywrightEnvironment.ts

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

It supports TypeScript out of the box and contains a lot of testing goodies like web-first assertions, parallelisation etc.
