### ISSUE TITLE
how to integrate with `@next/env`

### ISSUE THREAD

**Issue by chenrui333** [playwright-community/jest-playwright#774]
I have little bit trouble of integrating with the jest-playwright with nextjs.

I was trying to to apply the similar change as I did with jest unit tests ([nextjs doc ref](https://nextjs.org/docs/basic-features/environment-variables#test-environment-variables)) as below:

```
import { loadEnvConfig } from '@next/env';

module.exports = async () => {
  loadEnvConfig(process.env.PWD);
};
```

But it did not quite work out for jest-playwright integration, so I wonder what would be possible solution to integrate with nextjs config, thanks!

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro

For @playwright/test you can load it inside your playwright.config.ts which makes the environment variables available inside every test.
