### ISSUE TITLE
Support playwright v1.15.0

### ISSUE THREAD

**Issue by delbfinych** [playwright-community/jest-playwright#786]
There are features that would be nice to be supported:

- [Launch web server before running tests](https://playwright.dev/docs/test-advanced/#launching-a-development-web-server-during-the-tests)
- [test.parallel() run tests in the same file in parallel](https://playwright.dev/docs/api/class-test/#test-describe-parallel)

**Comment by mxschmitt** [comment]
jest-playwright is in maintenance mode, we recommend switching to the official test-runner: https://playwright.dev/docs/intro
