### ISSUE TITLE
Add strictness option to config

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#787]
**Is your feature request related to a problem? Please describe.**
We are using a lot of code that retrieves element handles to click them etc. But is beneficial to use strictness (see https://playwright.dev/docs/release-notes#%EF%B8%8F-new-strict-mode) since we then can catch faults in our selectors. E.g. if we have two unexpected elements on the same page with the same selector, it forces the developers to be more explicit in their selector to just match one element. The problem is that it looks bad/is cumbersome to add strictness to every line of code.

**Describe the solution you'd like**
It would be nice if the configuration file for testing (https://playwright.dev/docs/test-configuration) could add a strictness: true option so it defaults to being true for all selectors.

**Describe alternatives you've considered**
One option is to use [Locators](https://playwright.dev/docs/api/class-locator/). But they are more verbose and usually not necessary unless you are working on the same element over and over.

**Comment by mxschmitt** [comment]
You should be able to specify it in the config like that:

```
contextOptions: {
      strictSelectors: true
}
```

See here: https://github.com/playwright-community/jest-playwright#options
