### ISSUE TITLE
Unable to switch to inner frame in playwright 

### ISSUE THREAD

**Issue by bhavyagowda144** [playwright-community/jest-playwright#789]
I am unable to locate any inner child frame, getting error like frame.waitselector:target closed

I have tried many possible solutions didn't worked yet 

First  I have to switch to parent frame  
Const handle=await page.$('frame.name')
Const frame =await handle.contentframe():
Await  frame .waitforselector(`${locator}`)

Above code it is working fine ,I am able to switch parent frame ..

But not able to switch to inner frame

 below code
const inner=await Frame.childframes()[0]
await inner.waitforselector(`${locator}`)

Above  line does not working.. 

Please let me know how to switch to inner frame

**Comment by mxschmitt** [comment]
For Playwright questions I'd recommend to file issues against Playwright itself: https://github.com/microsoft/playwright
