### ISSUE TITLE
Question: history.pushState instead of full page load?

### ISSUE THREAD

**Issue by IanVS** [playwright-community/jest-playwright#791]
**Is your feature request related to a problem? Please describe.**
I'm testing a client-routed app, and would love to be able to use `history.pushState` to navigate between tests, rather than a full browser page load each test.  Is that something that's possible?  Or, does each test need to do a full navigation?

**Describe the solution you'd like**
Be able to client-side navigate to urls for each test.

**Describe alternatives you've considered**
I'm new to playwright, so maybe there's a way to do this I don't know about.  

**Additional context**
This is in a storybook test-runner test.  See https://github.com/storybookjs/test-runner/issues/64.

**Comment by mxschmitt** [comment]
For Playwright related questions I'd recommend to file an issue against Playwright itself: https://github.com/microsoft/playwright

**Comment by IanVS** [comment]
Oh ok, thanks.  I thought that the jest-playwright was what loaded up each test in a playwright window.  I don't know much about how any of it works, to be honest.
