### ISSUE TITLE
how to specify record starting point

### ISSUE THREAD

**Issue by wanghaisheng** [playwright-community/jest-playwright#798]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS or Windows]
 - Playwright version [e.g. 1.1.1]
 - jest-playwright version [e.g. 1.0.0]

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
<enter your Jest config here>
```

**Additional context**

i have set networkidle ,so when network is bad  we can get long blank video like this,if i want to record start when page success loaded
how

https://user-images.githubusercontent.com/2363295/169873440-c5661954-2179-48a8-85d2-008b23b76542.mp4

**Comment by mxschmitt** [comment]
Its not possible to specify a recording starting point, this is a Playwright limitation, see here for the upstream feature request: https://github.com/microsoft/playwright/issues/4821

**Comment by wanghaisheng** [comment]
i use track instead due to poor quality of default record
