### ISSUE TITLE
Test suites fail to lauch after upgrading playwright to 1.23.0 version

### ISSUE THREAD

**Issue by volodya315** [playwright-community/jest-playwright#802]
**Describe the bug**
After updating Playwright to version 1.23.0 it's impossible to run any tests. You will always receive the TypeError and stacktrace leads to teardown() method inside PlaywrightEnvironment.js
```
● Test suite failed to run    
TypeError: The "listener" argument must be of type function. Received undefined      
    at Page.removeListener (node_modules/playwright-core/lib/client/joiningEventEmitter.js:59:27)      
    at Page.removeListener (node_modules/playwright-core/lib/client/page.js:798:11)      
    at PlaywrightEnvironment.teardown (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:228:62)
    at runMicrotasks (<anonymous>)
```
After downgrading Playwright to version 1.22.2 tests run like a charm

**To Reproduce**
1. Update playwright to version 1.23.0
2. Run any test suite

**Expected behavior**
Test suite run starts

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, MacOS 12.4
 - Playwright version 1.23.0
 - jest-playwright version 1.7.2

**Jest configuration (`jest.config.js`):**

 ```js
module.exports = {
    "preset": "jest-playwright-preset",
    "testRunner": "jasmine2",
    "testMatch": ["**/__tests__/**/*.+(ts|js)", "**/?(*.)+(spec|test).+(ts|js)"],
    "verbose": true,
    "setupFilesAfterEnv": [
        "jest-allure/dist/setup",
        "./config.js",
        "./customMatchers.js",
        "./jest.setup.js"
    ]
}
```

**Comment by yehuda-goose-miller** [comment]
I'm experiencing the same issue

**Comment by volodya315** [comment]
I can definetely agree with @Gorodb, that updating Playwright to version 1.23.1 solves the issue.
This report is now obsolete

**Comment by yehuda-goose-miller** [comment]
Same with me. 1.23.1 resolved it.
