### ISSUE TITLE
Error when using custom Jest runner with selector engine: "shadow" selector engine has been already registered

### ISSUE THREAD

**Issue by thernstig** [playwright-community/jest-playwright#99]
**UPDATED**

Getting an error when using custom Jest runner with selector engine: `"shadow" selector engine has been already registered`. See repro in comments below.

**Original problem below. After update, solved by upgrading also Playwright.**

~~Just upgraded to latest jest-playwright (0.1.1) and get this when running:~~
 
```sh
FAIL   E2E  tests/e2e/suite/login/login.e2e.test.js
  ● Test suite failed to run

    Cannot evaluate a string with arguments

      at assert (../../node_modules/playwright-core/lib/helper.js:196:15)
      at Function.evaluationString (../../node_modules/playwright-core/lib/helper.js:25:13)
      at Selectors.register (../../node_modules/playwright-core/lib/selectors.js:31:40)
      at Selectors.<anonymous> (../../node_modules/playwright-core/lib/helper.js:55:31)
      at ../../node_modules/jest-playwright-preset/lib/utils.js:69:88
          at Array.map (<anonymous>)
      at Object.exports.getPlaywrightInstance (../../node_modules/jest-playwright-preset/lib/utils.js:69:41)
      at PlaywrightEnvironment.setup (../../node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:75:36)
```

~~My jest-playwright.config.js:~~

```javascript
const {
  selectorEngine,
} = require('query-selector-shadow-dom/plugins/playwright');

module.exports = {
  selectors: [{ name: 'shadow', script: selectorEngine }],
  server: {
    command: 'npm run start',
  },
};
```

**Comment by mxschmitt** [comment]
How do you install Playwright and which version of it are you using? It needs to be the latest once, because only this one is compatible with our latest release.

**Comment by thernstig** [comment]
Ok, will try the latest. But looking at your source code, it does not look like you changed how selector engines are set. It has changed in the latest Playwright: https://github.com/microsoft/playwright/blob/master/docs/selectors.md

That is the reason why I also not upgraded Playwright. But will try that now.

**Comment by mxschmitt** [comment]
We did it in #88 which should be already released.

> That is the reason why I also not upgraded Playwright. But will try that now.

awesome!

**Comment by thernstig** [comment]
Oh, you did! Then all good, we can close this one. Thanks!!

**Comment by thernstig** [comment]
@mxschmitt Hmm I get this error now. Using latest npm versions of both jest-playwright and playwright.

```sh
 PASS   E2E  tests/e2e/suite/login/login.e2e.test.js (15.765s)
  ● Console

    console.log tests/e2e/jest.setup.js:11
      12500

 FAIL   E2E  tests/e2e/suite/login/moo.e2e.test.js
  ● Test suite failed to run

    "shadow" selector engine has been already registered
```

**Comment by thernstig** [comment]
@mxschmitt Just making sure you saw my last comment with this ping (as you were so active at first so thinking you maybe missed it).

**Comment by mmarkelov** [comment]
@thernstig thanks for report? Could you provide your tests? And what is your config file?
```js
const {
  selectorEngine,
} = require('query-selector-shadow-dom/plugins/playwright');

module.exports = {
  selectors: [{ name: 'shadow', script: selectorEngine }],
  server: {
    command: 'npm run start',
  },
};
```

Is it actual configuration?

**Comment by thernstig** [comment]
Of course! I narrowed it down to what the problem is, I do not know why it happens, but you should hopefully be able to re-produce it.

I have 2 test files with this content:

```javascript
it('true', async () => {
  expect(true).toBe(true);
});
```

Here is `jest.config.js:`

```javascript
module.exports = {
  projects: [
    {
      rootDir: 'tests/e2e',
      preset: 'jest-playwright-preset',
      runner: '<rootDir>/util/serialJestRunner.js',
      setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
      transformIgnorePatterns: [
        '/node_modules/(?!(query-selector-shadow-dom)/)',
      ],
    },
  ],
};
```

Here is `jest-playwright.config.js` (inside the rootDir)

```javascript
const {
  selectorEngine,
} = require('query-selector-shadow-dom/plugins/playwright');

module.exports = {
  selectors: [{ name: 'shadow', script: selectorEngine }],
};
```

This fails like described above. Comment out `runner: '<rootDir>/util/serialJestRunner.js',` and both test cases will pass.

**Comment by thernstig** [comment]
Oh and here is `serialJestRunner.js` as a minimal example:

```javascript
// @ts-nocheck
/* eslint-disable import/no-extraneous-dependencies */
const Sequencer = require('@jest/test-sequencer').default;

class CustomSequencer extends Sequencer {
  // eslint-disable-next-line class-methods-use-this
  sort(tests) {
    return tests;
  }
}

module.exports = CustomSequencer;
```

**Comment by mmarkelov** [comment]
@thernstig yeah! There is something wrong, when I got **runner** option. I suppose I can do something like this:
```js
       selectors.map(({ name, script }) => {
          if (playwright.selectors._engines.get(name)) {
            return playwright.selectors.register(name, script)
          }
        }),
```

I suppose this should fix issue, but this kind of hacky solution. So idk. @mxschmitt what do you think?

**Comment by thernstig** [comment]
@mmarkelov @mxschmitt I agree it looks somewhat hacky, not sure what the proper solution would be though.

**Comment by thernstig** [comment]
I am unfortunately having big problem with this one, as it blocks me from actually using jest-playwright with custom selectors and a custom sequencer, which is a use case I need.

Would an idea be to implement the above as a temporary solution till you come up with something non-hackish? I would very much appreciate it :)

**Comment by mmarkelov** [comment]
@thernstig ok, I'll put PR to fix this soon and publish version with fix

**Comment by mmarkelov** [comment]
I will keep it open, cause now it's kind of hacky solution

**Comment by mmarkelov** [comment]
@thernstig should be fixed in **0.1.2**

**Comment by thernstig** [comment]
Amazing, thanks, will test it tomorrow.

**Comment by thernstig** [comment]
The workaround works 💯 Good job, and thanks. I also still agree a more robust solution should probably be used.
